//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BodyArchitect.Client.Module.Suplements {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SuplementsEntryStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SuplementsEntryStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BodyArchitect.Client.Module.Suplements.SuplementsEntryStrings", typeof(SuplementsEntryStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string ColumnSuplementName {
            get {
                return ResourceManager.GetString("ColumnSuplementName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplement types.
        /// </summary>
        public static string DefaultSuplementsName {
            get {
                return ResourceManager.GetString("DefaultSuplementsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete this entry.
        /// </summary>
        public static string DeleteThisEntryTip {
            get {
                return ResourceManager.GetString("DeleteThisEntryTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplements.
        /// </summary>
        public static string EntryTypeName {
            get {
                return ResourceManager.GetString("EntryTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you take any supplements, you can note all information about this fact like dosages and time..
        /// </summary>
        public static string EntryTypeShortDescription {
            get {
                return ResourceManager.GetString("EntryTypeShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot publish this supplements routine..
        /// </summary>
        public static string ErrCannotPublishSuppleDefinition {
            get {
                return ResourceManager.GetString("ErrCannotPublishSuppleDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete selected supplement types. Please see the log file. ErrorId: {0}..
        /// </summary>
        public static string ErrorCannotDeleteSuplementType {
            get {
                return ResourceManager.GetString("ErrorCannotDeleteSuplementType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured during saving..
        /// </summary>
        public static string ErrorDuringSuplementSaving {
            get {
                return ResourceManager.GetString("ErrorDuringSuplementSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot finish this operation..
        /// </summary>
        public static string Exception_StartSupplementsCycleWindow_ErrPreview {
            get {
                return ResourceManager.GetString("Exception_StartSupplementsCycleWindow_ErrPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation was too long. Please try later..
        /// </summary>
        public static string Exception_StartSupplementsCycleWindow_ErrPreviewTimeout {
            get {
                return ResourceManager.GetString("Exception_StartSupplementsCycleWindow_ErrPreviewTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot start this cycle.
        /// </summary>
        public static string Exception_StartSupplementsCycleWindow_OkClick_CannotStartCycle {
            get {
                return ResourceManager.GetString("Exception_StartSupplementsCycleWindow_OkClick_CannotStartCycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception occurred.
        /// </summary>
        public static string Exception_SupplementsCycleDefinitionEditorViewModel_Save {
            get {
                return ResourceManager.GetString("Exception_SupplementsCycleDefinitionEditorViewModel_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplements cycle has been started. Now you can go to the calendar to see the new entries..
        /// </summary>
        public static string Info_usrSupplementsCyclesView_rbtnStartCycle_Click_StartedCycle {
            get {
                return ResourceManager.GetString("Info_usrSupplementsCyclesView_rbtnStartCycle_Click_StartedCycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to remove selected row?.
        /// </summary>
        public static string QDeleteSuplementRow {
            get {
                return ResourceManager.GetString("QDeleteSuplementRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete selected supplement types?.
        /// </summary>
        public static string QDeleteSuplementType {
            get {
                return ResourceManager.GetString("QDeleteSuplementType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete this cycle?.
        /// </summary>
        public static string Question_usrSupplementsCyclesView_DoYouWantToDeleteCycle {
            get {
                return ResourceManager.GetString("Question_usrSupplementsCyclesView_DoYouWantToDeleteCycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Select a supplement type).
        /// </summary>
        public static string SelectSuplementType {
            get {
                return ResourceManager.GetString("SelectSuplementType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string StartSupplementsCycleWindow_OKButton_Start {
            get {
                return ResourceManager.GetString("StartSupplementsCycleWindow_OKButton_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start a new cycle.
        /// </summary>
        public static string StartSupplementsCycleWindow_Title {
            get {
                return ResourceManager.GetString("StartSupplementsCycleWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cardio.
        /// </summary>
        public static string StartSupplementsCycleWindow_TrainingType_Cardio {
            get {
                return ResourceManager.GetString("StartSupplementsCycleWindow_TrainingType_Cardio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string StartSupplementsCycleWindow_TrainingType_None {
            get {
                return ResourceManager.GetString("StartSupplementsCycleWindow_TrainingType_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strength training.
        /// </summary>
        public static string StartSupplementsCycleWindow_TrainingType_Strength {
            get {
                return ResourceManager.GetString("StartSupplementsCycleWindow_TrainingType_Strength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both.
        /// </summary>
        public static string StartSupplementsCycleWindow_TrainingType_StrengthAndCardio {
            get {
                return ResourceManager.GetString("StartSupplementsCycleWindow_TrainingType_StrengthAndCardio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Choose supplements routine).
        /// </summary>
        public static string StartSupplementsCycleWindow_Watermark_ChooseSupplementDefinitions {
            get {
                return ResourceManager.GetString("StartSupplementsCycleWindow_Watermark_ChooseSupplementDefinitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suplement name cannot be empty..
        /// </summary>
        public static string Suplement_Name_Empty {
            get {
                return ResourceManager.GetString("Suplement_Name_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suplement name is too long..
        /// </summary>
        public static string Suplement_Name_Length {
            get {
                return ResourceManager.GetString("Suplement_Name_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suplement name must be unique..
        /// </summary>
        public static string Suplement_Name_Unique {
            get {
                return ResourceManager.GetString("Suplement_Name_Unique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dosage.
        /// </summary>
        public static string SuplementGrid_DosageColumn {
            get {
                return ResourceManager.GetString("SuplementGrid_DosageColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dosage type.
        /// </summary>
        public static string SuplementGrid_DosageTypeColumn {
            get {
                return ResourceManager.GetString("SuplementGrid_DosageTypeColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string SuplementGrid_InfoColumn {
            get {
                return ResourceManager.GetString("SuplementGrid_InfoColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string SuplementGrid_NameColumn {
            get {
                return ResourceManager.GetString("SuplementGrid_NameColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplement.
        /// </summary>
        public static string SuplementGrid_SuplementColumn {
            get {
                return ResourceManager.GetString("SuplementGrid_SuplementColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string SuplementGrid_TimeColumn {
            get {
                return ResourceManager.GetString("SuplementGrid_TimeColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        public static string SuplementsEntryStrings_Content_Preview {
            get {
                return ResourceManager.GetString("SuplementsEntryStrings_Content_Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your training days:.
        /// </summary>
        public static string SuplementsEntryStrings_Content_SelectDays {
            get {
                return ResourceManager.GetString("SuplementsEntryStrings_Content_SelectDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date:.
        /// </summary>
        public static string SuplementsEntryStrings_Content_StartDate {
            get {
                return ResourceManager.GetString("SuplementsEntryStrings_Content_StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your weight:.
        /// </summary>
        public static string SuplementsEntryStrings_Content_Weight {
            get {
                return ResourceManager.GetString("SuplementsEntryStrings_Content_Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters.
        /// </summary>
        public static string SuplementsEntryStrings_Header_Parameters {
            get {
                return ResourceManager.GetString("SuplementsEntryStrings_Header_Parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        public static string SuplementsEntryStrings_Header_Preview {
            get {
                return ResourceManager.GetString("SuplementsEntryStrings_Header_Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date:.
        /// </summary>
        public static string SuplementsEntryStrings_Label_StartDate {
            get {
                return ResourceManager.GetString("SuplementsEntryStrings_Label_StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How long:.
        /// </summary>
        public static string SuplementsEntryStrings_Label_TotalWeeks {
            get {
                return ResourceManager.GetString("SuplementsEntryStrings_Label_TotalWeeks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to weeks.
        /// </summary>
        public static string SuplementsEntryStrings_Label_WeeksPostFix {
            get {
                return ResourceManager.GetString("SuplementsEntryStrings_Label_WeeksPostFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click the Preview button to see simulation of this supplement cycle. No changes will be applied to your calendar..
        /// </summary>
        public static string SuplementsEntryStrings_Text_ClickPreview {
            get {
                return ResourceManager.GetString("SuplementsEntryStrings_Text_ClickPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows add a new supplement type to the database..
        /// </summary>
        public static string SuplementsViewWindow_AddBTN {
            get {
                return ResourceManager.GetString("SuplementsViewWindow_AddBTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deletes selected supplement types permanently..
        /// </summary>
        public static string SuplementsViewWindow_DeleteBTN {
            get {
                return ResourceManager.GetString("SuplementsViewWindow_DeleteBTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows edit selected supplement type..
        /// </summary>
        public static string SuplementsViewWindow_EditBTN {
            get {
                return ResourceManager.GetString("SuplementsViewWindow_EditBTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of all supplement types in the database..
        /// </summary>
        public static string SuplementsViewWindow_SuplementsListView {
            get {
                return ResourceManager.GetString("SuplementsViewWindow_SuplementsListView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional information about this supplement..
        /// </summary>
        public static string SuplementTypeEditor_CommentTXT {
            get {
                return ResourceManager.GetString("SuplementTypeEditor_CommentTXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of the supplement. Must be unique and cannot be empty..
        /// </summary>
        public static string SuplementTypeEditor_NameTXT {
            get {
                return ResourceManager.GetString("SuplementTypeEditor_NameTXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplement types....
        /// </summary>
        public static string SuplementTypesMenu {
            get {
                return ResourceManager.GetString("SuplementTypesMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SuplementId cannot be empty.
        /// </summary>
        public static string SupplementItemViewModel_columnName_EmptyId {
            get {
                return ResourceManager.GetString("SupplementItemViewModel_columnName_EmptyId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Author.
        /// </summary>
        public static string SupplementsCycleDefinitionEditorView_Content_Author {
            get {
                return ResourceManager.GetString("SupplementsCycleDefinitionEditorView_Content_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Difficulty.
        /// </summary>
        public static string SupplementsCycleDefinitionEditorView_Content_Difficult {
            get {
                return ResourceManager.GetString("SupplementsCycleDefinitionEditorView_Content_Difficult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Language.
        /// </summary>
        public static string SupplementsCycleDefinitionEditorView_Content_Language {
            get {
                return ResourceManager.GetString("SupplementsCycleDefinitionEditorView_Content_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Name.
        /// </summary>
        public static string SupplementsCycleDefinitionEditorView_Content_Name {
            get {
                return ResourceManager.GetString("SupplementsCycleDefinitionEditorView_Content_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Purpose.
        /// </summary>
        public static string SupplementsCycleDefinitionEditorView_Content_Purpose {
            get {
                return ResourceManager.GetString("SupplementsCycleDefinitionEditorView_Content_Purpose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Url.
        /// </summary>
        public static string SupplementsCycleDefinitionEditorView_Content_Url {
            get {
                return ResourceManager.GetString("SupplementsCycleDefinitionEditorView_Content_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string SupplementsCycleDefinitionEditorView_Header_Description {
            get {
                return ResourceManager.GetString("SupplementsCycleDefinitionEditorView_Header_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string SupplementsCycleDefinitionEditorView_Header_Details {
            get {
                return ResourceManager.GetString("SupplementsCycleDefinitionEditorView_Header_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string SupplementsCycleDefinitionEditorView_Header_Edit {
            get {
                return ResourceManager.GetString("SupplementsCycleDefinitionEditorView_Header_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editor.
        /// </summary>
        public static string SupplementsCycleDefinitionEditorView_Header_Editor {
            get {
                return ResourceManager.GetString("SupplementsCycleDefinitionEditorView_Header_Editor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string SupplementsCycleDefinitionEditorView_Header_Information {
            get {
                return ResourceManager.GetString("SupplementsCycleDefinitionEditorView_Header_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add measurements.
        /// </summary>
        public static string SupplementsCycleDefinitionEditorView_Label_AddMeasurements {
            get {
                return ResourceManager.GetString("SupplementsCycleDefinitionEditorView_Label_AddMeasurements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a suplement.
        /// </summary>
        public static string SupplementsCycleDefinitionEditorView_Label_AddSuplement {
            get {
                return ResourceManager.GetString("SupplementsCycleDefinitionEditorView_Label_AddSuplement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a week.
        /// </summary>
        public static string SupplementsCycleDefinitionEditorView_Label_AddWeek {
            get {
                return ResourceManager.GetString("SupplementsCycleDefinitionEditorView_Label_AddWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string SupplementsCycleDefinitionEditorView_Label_Delete {
            get {
                return ResourceManager.GetString("SupplementsCycleDefinitionEditorView_Label_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SupplementsCycleDefinitionEditorView_Label_Save {
            get {
                return ResourceManager.GetString("SupplementsCycleDefinitionEditorView_Label_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a language.
        /// </summary>
        public static string SupplementsCycleDefinitionEditorView_Watermark_SelectLanguage {
            get {
                return ResourceManager.GetString("SupplementsCycleDefinitionEditorView_Watermark_SelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author can have max. 100 characters.
        /// </summary>
        public static string SupplementsCycleDefinitionEditorViewModel_Author_Length_Validator {
            get {
                return ResourceManager.GetString("SupplementsCycleDefinitionEditorViewModel_Author_Length_Validator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cycle editor:.
        /// </summary>
        public static string SupplementsCycleDefinitionEditorViewModel_Header_CEditor {
            get {
                return ResourceManager.GetString("SupplementsCycleDefinitionEditorViewModel_Header_CEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weeks: {0}-{1}.
        /// </summary>
        public static string SupplementsCycleDefinitionEditorViewModel_Header_Weeks {
            get {
                return ResourceManager.GetString("SupplementsCycleDefinitionEditorViewModel_Header_Weeks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect language.
        /// </summary>
        public static string SupplementsCycleDefinitionEditorViewModel_Language_Validator {
            get {
                return ResourceManager.GetString("SupplementsCycleDefinitionEditorViewModel_Language_Validator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measurements.
        /// </summary>
        public static string SupplementsCycleDefinitionEditorViewModel_Measurements {
            get {
                return ResourceManager.GetString("SupplementsCycleDefinitionEditorViewModel_Measurements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a name (max. 100 characters).
        /// </summary>
        public static string SupplementsCycleDefinitionEditorViewModel_Name_Length_Validator {
            get {
                return ResourceManager.GetString("SupplementsCycleDefinitionEditorViewModel_Name_Length_Validator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Select a supplement).
        /// </summary>
        public static string SupplementsCycleDefinitionEditorViewModel_Update_SelectSuplement {
            get {
                return ResourceManager.GetString("SupplementsCycleDefinitionEditorViewModel_Update_SelectSuplement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url is too long.
        /// </summary>
        public static string SupplementsCycleDefinitionEditorViewModel_Url_Length_Validator {
            get {
                return ResourceManager.GetString("SupplementsCycleDefinitionEditorViewModel_Url_Length_Validator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string SupplementsCycleDefinitionHtmlExporter_BuildDescription {
            get {
                return ResourceManager.GetString("SupplementsCycleDefinitionHtmlExporter_BuildDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        public static string SupplementsCycleDefinitionHtmlExporter_BuildInfo_Author {
            get {
                return ResourceManager.GetString("SupplementsCycleDefinitionHtmlExporter_BuildInfo_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation date.
        /// </summary>
        public static string SupplementsCycleDefinitionHtmlExporter_BuildInfo_CreationDate {
            get {
                return ResourceManager.GetString("SupplementsCycleDefinitionHtmlExporter_BuildInfo_CreationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string SupplementsCycleDefinitionHtmlExporter_BuildInfo_Details {
            get {
                return ResourceManager.GetString("SupplementsCycleDefinitionHtmlExporter_BuildInfo_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Difficulty.
        /// </summary>
        public static string SupplementsCycleDefinitionHtmlExporter_BuildInfo_Difficulty {
            get {
                return ResourceManager.GetString("SupplementsCycleDefinitionHtmlExporter_BuildInfo_Difficulty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to per 10 kg.
        /// </summary>
        public static string SupplementsCycleDefinitionHtmlExporter_BuildInfo_DosagePer10Kg {
            get {
                return ResourceManager.GetString("SupplementsCycleDefinitionHtmlExporter_BuildInfo_DosagePer10Kg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How long.
        /// </summary>
        public static string SupplementsCycleDefinitionHtmlExporter_BuildInfo_HowLong {
            get {
                return ResourceManager.GetString("SupplementsCycleDefinitionHtmlExporter_BuildInfo_HowLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string SupplementsCycleDefinitionHtmlExporter_BuildInfo_Info {
            get {
                return ResourceManager.GetString("SupplementsCycleDefinitionHtmlExporter_BuildInfo_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string SupplementsCycleDefinitionHtmlExporter_BuildInfo_Language {
            get {
                return ResourceManager.GetString("SupplementsCycleDefinitionHtmlExporter_BuildInfo_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purpose.
        /// </summary>
        public static string SupplementsCycleDefinitionHtmlExporter_BuildInfo_Purpose {
            get {
                return ResourceManager.GetString("SupplementsCycleDefinitionHtmlExporter_BuildInfo_Purpose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url.
        /// </summary>
        public static string SupplementsCycleDefinitionHtmlExporter_BuildInfo_Url {
            get {
                return ResourceManager.GetString("SupplementsCycleDefinitionHtmlExporter_BuildInfo_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;TR class=&apos;{1}&apos;&gt;&lt;TD&gt;Week {0}&lt;/TD&gt;.
        /// </summary>
        public static string SupplementsCycleDefinitionHtmlExporter_BuildInfo_Week {
            get {
                return ResourceManager.GetString("SupplementsCycleDefinitionHtmlExporter_BuildInfo_Week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How long.
        /// </summary>
        public static string SupplementsCycleDefinitionHtmlExporter_BuildInfo_Weeks {
            get {
                return ResourceManager.GetString("SupplementsCycleDefinitionHtmlExporter_BuildInfo_Weeks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} weeks.
        /// </summary>
        public static string SupplementsCycleDefinitionHtmlExporter_BuildInfo_Weeks_Value {
            get {
                return ResourceManager.GetString("SupplementsCycleDefinitionHtmlExporter_BuildInfo_Weeks_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string SupplementsCycleDefinitionHtmlExporter_Column_Comment {
            get {
                return ResourceManager.GetString("SupplementsCycleDefinitionHtmlExporter_Column_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To publish supplements cycle definition you must have at least {0} supplements entries in your calendar..
        /// </summary>
        public static string SupplementsCycleDefinitions_Publish_ErrProfileRank {
            get {
                return ResourceManager.GetString("SupplementsCycleDefinitions_Publish_ErrProfileRank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        public static string SupplementsCyclesList_Header_Author {
            get {
                return ResourceManager.GetString("SupplementsCyclesList_Header_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string SupplementsCyclesList_Header_Name {
            get {
                return ResourceManager.GetString("SupplementsCyclesList_Header_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating.
        /// </summary>
        public static string SupplementsCyclesList_Header_Rating {
            get {
                return ResourceManager.GetString("SupplementsCyclesList_Header_Rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string SupplementsCyclesList_Header_Status {
            get {
                return ResourceManager.GetString("SupplementsCyclesList_Header_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains supplements, that could be illegal in your country..
        /// </summary>
        public static string SupplementsCyclesList_ToolTip_CanBeIllegal {
            get {
                return ResourceManager.GetString("SupplementsCyclesList_ToolTip_CanBeIllegal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains legal supplements only..
        /// </summary>
        public static string SupplementsCyclesList_ToolTip_IsLegal {
            get {
                return ResourceManager.GetString("SupplementsCyclesList_ToolTip_IsLegal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cycle.
        /// </summary>
        public static string SupplementsCyclesView_Header_Cycles {
            get {
                return ResourceManager.GetString("SupplementsCyclesView_Header_Cycles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SupplementsDefinitionNewName {
            get {
                return ResourceManager.GetString("SupplementsDefinitionNewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplements.
        /// </summary>
        public static string SupplementsModule_CreateRibbon_Header_Supplements {
            get {
                return ResourceManager.GetString("SupplementsModule_CreateRibbon_Header_Supplements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cycles.
        /// </summary>
        public static string SupplementsModule_CreateRibbon_Label_Cycles {
            get {
                return ResourceManager.GetString("SupplementsModule_CreateRibbon_Label_Cycles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BodyArchitect - workout log and social application created for professional bodybuilders..
        /// </summary>
        public static string SupplementsModule_ShareToSocial_Caption {
            get {
                return ResourceManager.GetString("SupplementsModule_ShareToSocial_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date: {0}&lt;br/&gt;.
        /// </summary>
        public static string SupplementsModule_ShareToSocial_Date {
            get {
                return ResourceManager.GetString("SupplementsModule_ShareToSocial_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1}: &lt;i&gt;{2:.##} {3}&lt;/i&gt;&lt;br/&gt;.
        /// </summary>
        public static string SupplementsModule_ShareToSocial_Dosage {
            get {
                return ResourceManager.GetString("SupplementsModule_ShareToSocial_Dosage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New entry: Supplements.
        /// </summary>
        public static string SupplementsModule_ShareToSocial_Name {
            get {
                return ResourceManager.GetString("SupplementsModule_ShareToSocial_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string SupplementsView_Header_Edit {
            get {
                return ResourceManager.GetString("SupplementsView_Header_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplements.
        /// </summary>
        public static string SupplementsView_Header_Supplements {
            get {
                return ResourceManager.GetString("SupplementsView_Header_Supplements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplements.
        /// </summary>
        public static string SupplementsView_Header_Supplements_xamlCs {
            get {
                return ResourceManager.GetString("SupplementsView_Header_Supplements_xamlCs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string SupplementsView_Header_Type {
            get {
                return ResourceManager.GetString("SupplementsView_Header_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string SupplementsView_NameColumnHeader {
            get {
                return ResourceManager.GetString("SupplementsView_NameColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use _this week for longer cycles.
        /// </summary>
        public static string usrSupplementCycleWeekEditor_CHK_IsRepetitable {
            get {
                return ResourceManager.GetString("usrSupplementCycleWeekEditor_CHK_IsRepetitable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Comment:.
        /// </summary>
        public static string usrSupplementCycleWeekEditor_Content_Comment {
            get {
                return ResourceManager.GetString("usrSupplementCycleWeekEditor_Content_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _End:.
        /// </summary>
        public static string usrSupplementCycleWeekEditor_Content_End {
            get {
                return ResourceManager.GetString("usrSupplementCycleWeekEditor_Content_End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Name:.
        /// </summary>
        public static string usrSupplementCycleWeekEditor_Content_Name {
            get {
                return ResourceManager.GetString("usrSupplementCycleWeekEditor_Content_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Start:.
        /// </summary>
        public static string usrSupplementCycleWeekEditor_Content_Start {
            get {
                return ResourceManager.GetString("usrSupplementCycleWeekEditor_Content_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User, when starting a new cycle, can specify how long it should take. If he choose longer period of time than defined in this routine, BodyArchitect will repeat existing weeks automatically to fill entire time period. If some weeks shouldn’t be repeated, then unselect this option. If you unselect it for all weeks, then user will not be able to extend the cycle..
        /// </summary>
        public static string usrSupplementCycleWeekEditor_Help_IsRepetitable {
            get {
                return ResourceManager.GetString("usrSupplementCycleWeekEditor_Help_IsRepetitable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Comment:.
        /// </summary>
        public static string usrSupplementsCycleDosageEditor_Content_Comment {
            get {
                return ResourceManager.GetString("usrSupplementsCycleDosageEditor_Content_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Dosage:.
        /// </summary>
        public static string usrSupplementsCycleDosageEditor_Content_Dosage {
            get {
                return ResourceManager.GetString("usrSupplementsCycleDosageEditor_Content_Dosage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _How often:.
        /// </summary>
        public static string usrSupplementsCycleDosageEditor_Content_HowOften {
            get {
                return ResourceManager.GetString("usrSupplementsCycleDosageEditor_Content_HowOften", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Supplement:.
        /// </summary>
        public static string usrSupplementsCycleDosageEditor_Content_Supplement {
            get {
                return ResourceManager.GetString("usrSupplementsCycleDosageEditor_Content_Supplement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _When:.
        /// </summary>
        public static string usrSupplementsCycleDosageEditor_Content_When {
            get {
                return ResourceManager.GetString("usrSupplementsCycleDosageEditor_Content_When", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplement name.
        /// </summary>
        public static string usrSupplementsCycleDosageEditor_Watermark_SupplementName {
            get {
                return ResourceManager.GetString("usrSupplementsCycleDosageEditor_Watermark_SupplementName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} {2}.
        /// </summary>
        public static string usrSupplementsCyclePreview_generateStatistics_Item {
            get {
                return ResourceManager.GetString("usrSupplementsCyclePreview_generateStatistics_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cycle summary:.
        /// </summary>
        public static string usrSupplementsCyclePreview_Text_CycleSummary {
            get {
                return ResourceManager.GetString("usrSupplementsCyclePreview_Text_CycleSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ascending.
        /// </summary>
        public static string usrSupplementsCyclesView_Header_Ascending {
            get {
                return ResourceManager.GetString("usrSupplementsCyclesView_Header_Ascending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cycle.
        /// </summary>
        public static string usrSupplementsCyclesView_Header_Cycle {
            get {
                return ResourceManager.GetString("usrSupplementsCyclesView_Header_Cycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descending.
        /// </summary>
        public static string usrSupplementsCyclesView_Header_Descending {
            get {
                return ResourceManager.GetString("usrSupplementsCyclesView_Header_Descending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string usrSupplementsCyclesView_Header_Edit {
            get {
                return ResourceManager.GetString("usrSupplementsCyclesView_Header_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorities.
        /// </summary>
        public static string usrSupplementsCyclesView_Header_Favorities {
            get {
                return ResourceManager.GetString("usrSupplementsCyclesView_Header_Favorities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My cycles.
        /// </summary>
        public static string usrSupplementsCyclesView_Header_MyCycles {
            get {
                return ResourceManager.GetString("usrSupplementsCyclesView_Header_MyCycles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operations.
        /// </summary>
        public static string usrSupplementsCyclesView_Header_Operations {
            get {
                return ResourceManager.GetString("usrSupplementsCyclesView_Header_Operations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string usrSupplementsCyclesView_Header_Search_RibbonGroup {
            get {
                return ResourceManager.GetString("usrSupplementsCyclesView_Header_Search_RibbonGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string usrSupplementsCyclesView_Header_Search_RibbonTab {
            get {
                return ResourceManager.GetString("usrSupplementsCyclesView_Header_Search_RibbonTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string usrSupplementsCyclesView_Header_Search_TabItem {
            get {
                return ResourceManager.GetString("usrSupplementsCyclesView_Header_Search_TabItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort order.
        /// </summary>
        public static string usrSupplementsCyclesView_Header_SortOrder {
            get {
                return ResourceManager.GetString("usrSupplementsCyclesView_Header_SortOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string usrSupplementsCyclesView_Label_Add {
            get {
                return ResourceManager.GetString("usrSupplementsCyclesView_Label_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clone.
        /// </summary>
        public static string usrSupplementsCyclesView_Label_Clone {
            get {
                return ResourceManager.GetString("usrSupplementsCyclesView_Label_Clone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string usrSupplementsCyclesView_Label_Delete {
            get {
                return ResourceManager.GetString("usrSupplementsCyclesView_Label_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string usrSupplementsCyclesView_Label_Edit {
            get {
                return ResourceManager.GetString("usrSupplementsCyclesView_Label_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More.
        /// </summary>
        public static string usrSupplementsCyclesView_Label_More {
            get {
                return ResourceManager.GetString("usrSupplementsCyclesView_Label_More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string usrSupplementsCyclesView_Label_New {
            get {
                return ResourceManager.GetString("usrSupplementsCyclesView_Label_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        public static string usrSupplementsCyclesView_Label_Order {
            get {
                return ResourceManager.GetString("usrSupplementsCyclesView_Label_Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish.
        /// </summary>
        public static string usrSupplementsCyclesView_Label_Publish {
            get {
                return ResourceManager.GetString("usrSupplementsCyclesView_Label_Publish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string usrSupplementsCyclesView_Label_Remove {
            get {
                return ResourceManager.GetString("usrSupplementsCyclesView_Label_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string usrSupplementsCyclesView_Label_Search {
            get {
                return ResourceManager.GetString("usrSupplementsCyclesView_Label_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort order.
        /// </summary>
        public static string usrSupplementsCyclesView_Label_SortOrder {
            get {
                return ResourceManager.GetString("usrSupplementsCyclesView_Label_SortOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start cycle.
        /// </summary>
        public static string usrSupplementsCyclesView_Label_StartCycle {
            get {
                return ResourceManager.GetString("usrSupplementsCyclesView_Label_StartCycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string usrSupplementsCyclesView_Label_View {
            get {
                return ResourceManager.GetString("usrSupplementsCyclesView_Label_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deletes entire row.
        /// </summary>
        public static string usrSupplementsEntry_DeleteRowButtonTip {
            get {
                return ResourceManager.GetString("usrSupplementsEntry_DeleteRowButtonTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dosage.
        /// </summary>
        public static string usrSupplementsEntry_DosageColumnHeader {
            get {
                return ResourceManager.GetString("usrSupplementsEntry_DosageColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dosage type.
        /// </summary>
        public static string usrSupplementsEntry_DosageTypeColumnHeader {
            get {
                return ResourceManager.GetString("usrSupplementsEntry_DosageTypeColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string usrSupplementsEntry_Header_Comment {
            get {
                return ResourceManager.GetString("usrSupplementsEntry_Header_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remind.
        /// </summary>
        public static string usrSupplementsEntry_Header_Remind {
            get {
                return ResourceManager.GetString("usrSupplementsEntry_Header_Remind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string usrSupplementsEntry_InfoColumnHeader {
            get {
                return ResourceManager.GetString("usrSupplementsEntry_InfoColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string usrSupplementsEntry_NameColumnHeader {
            get {
                return ResourceManager.GetString("usrSupplementsEntry_NameColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplement.
        /// </summary>
        public static string usrSupplementsEntry_SupplementsColumnHeader {
            get {
                return ResourceManager.GetString("usrSupplementsEntry_SupplementsColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplements.
        /// </summary>
        public static string usrSupplementsEntry_SupplementsHeader {
            get {
                return ResourceManager.GetString("usrSupplementsEntry_SupplementsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !.
        /// </summary>
        public static string usrSupplementsEntry_Text_ExclamationMark {
            get {
                return ResourceManager.GetString("usrSupplementsEntry_Text_ExclamationMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string usrSupplementsEntry_TimeColumnHeader {
            get {
                return ResourceManager.GetString("usrSupplementsEntry_TimeColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When.
        /// </summary>
        public static string usrSupplementsEntry_TimeTypeColumnHeader {
            get {
                return ResourceManager.GetString("usrSupplementsEntry_TimeTypeColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can put some comment here.
        /// </summary>
        public static string usrSupplementsEntry_Watermark_Comment {
            get {
                return ResourceManager.GetString("usrSupplementsEntry_Watermark_Comment", resourceCulture);
            }
        }
    }
}
