//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BodyArchitect.Client.Module.Blog.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BlogEntryStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BlogEntryStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BodyArchitect.Client.Module.Blog.Localization.BlogEntryStrings", typeof(BlogEntryStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom.
        /// </summary>
        internal static string Align_Bottom {
            get {
                return ResourceManager.GetString("Align_Bottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center.
        /// </summary>
        internal static string Align_Center {
            get {
                return ResourceManager.GetString("Align_Center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string Align_Default {
            get {
                return ResourceManager.GetString("Align_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        internal static string Align_Left {
            get {
                return ResourceManager.GetString("Align_Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right.
        /// </summary>
        internal static string Align_Right {
            get {
                return ResourceManager.GetString("Align_Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top.
        /// </summary>
        internal static string Align_Top {
            get {
                return ResourceManager.GetString("Align_Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blog.
        /// </summary>
        internal static string BlogCalendarDayContent_Name {
            get {
                return ResourceManager.GetString("BlogCalendarDayContent_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BodyArchitect - workout log and social application created for professional bodybuilders..
        /// </summary>
        internal static string BlogModule_ShareToSocial_Caption {
            get {
                return ResourceManager.GetString("BlogModule_ShareToSocial_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date: {0}&lt;br/&gt;.
        /// </summary>
        internal static string BlogModule_ShareToSocial_Description {
            get {
                return ResourceManager.GetString("BlogModule_ShareToSocial_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New entry: Blog.
        /// </summary>
        internal static string BlogModule_ShareToSocial_Name {
            get {
                return ResourceManager.GetString("BlogModule_ShareToSocial_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bold.
        /// </summary>
        internal static string Button_Bold {
            get {
                return ResourceManager.GetString("Button_Bold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        internal static string Button_Browse {
            get {
                return ResourceManager.GetString("Button_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulleted List.
        /// </summary>
        internal static string Button_BulletedList {
            get {
                return ResourceManager.GetString("Button_BulletedList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Style.
        /// </summary>
        internal static string Button_ClearStyle {
            get {
                return ResourceManager.GetString("Button_ClearStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Mode.
        /// </summary>
        internal static string Button_CodeMode {
            get {
                return ResourceManager.GetString("Button_CodeMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font Color.
        /// </summary>
        internal static string Button_FontColor {
            get {
                return ResourceManager.GetString("Button_FontColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indent.
        /// </summary>
        internal static string Button_Indent {
            get {
                return ResourceManager.GetString("Button_Indent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Hyperlink.
        /// </summary>
        internal static string Button_InsertHyperlink {
            get {
                return ResourceManager.GetString("Button_InsertHyperlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Image.
        /// </summary>
        internal static string Button_InsertImage {
            get {
                return ResourceManager.GetString("Button_InsertImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Table.
        /// </summary>
        internal static string Button_InsertTable {
            get {
                return ResourceManager.GetString("Button_InsertTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italic.
        /// </summary>
        internal static string Button_Italic {
            get {
                return ResourceManager.GetString("Button_Italic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Justify Center.
        /// </summary>
        internal static string Button_JustifyCenter {
            get {
                return ResourceManager.GetString("Button_JustifyCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Justify Full.
        /// </summary>
        internal static string Button_JustifyFull {
            get {
                return ResourceManager.GetString("Button_JustifyFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Justify Left.
        /// </summary>
        internal static string Button_JustifyLeft {
            get {
                return ResourceManager.GetString("Button_JustifyLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Justify Right.
        /// </summary>
        internal static string Button_JustifyRight {
            get {
                return ResourceManager.GetString("Button_JustifyRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line Color.
        /// </summary>
        internal static string Button_LineColor {
            get {
                return ResourceManager.GetString("Button_LineColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numbered List.
        /// </summary>
        internal static string Button_NumberedList {
            get {
                return ResourceManager.GetString("Button_NumberedList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outdent.
        /// </summary>
        internal static string Button_Outdent {
            get {
                return ResourceManager.GetString("Button_Outdent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string Button_Refresh {
            get {
                return ResourceManager.GetString("Button_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscript.
        /// </summary>
        internal static string Button_Subscript {
            get {
                return ResourceManager.GetString("Button_Subscript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Superscript.
        /// </summary>
        internal static string Button_Superscript {
            get {
                return ResourceManager.GetString("Button_Superscript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Underline.
        /// </summary>
        internal static string Button_Underline {
            get {
                return ResourceManager.GetString("Button_Underline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom In.
        /// </summary>
        internal static string Button_ZoomIn {
            get {
                return ResourceManager.GetString("Button_ZoomIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom Out.
        /// </summary>
        internal static string Button_ZoomOut {
            get {
                return ResourceManager.GetString("Button_ZoomOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string Cmd_Copy {
            get {
                return ResourceManager.GetString("Cmd_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        internal static string Cmd_Cut {
            get {
                return ResourceManager.GetString("Cmd_Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Cmd_Delete {
            get {
                return ResourceManager.GetString("Cmd_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        internal static string Cmd_Paste {
            get {
                return ResourceManager.GetString("Cmd_Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo.
        /// </summary>
        internal static string Cmd_Redo {
            get {
                return ResourceManager.GetString("Cmd_Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        internal static string Cmd_SelectAll {
            get {
                return ResourceManager.GetString("Cmd_SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        internal static string Cmd_Undo {
            get {
                return ResourceManager.GetString("Cmd_Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blog.
        /// </summary>
        internal static string EntryTypeName {
            get {
                return ResourceManager.GetString("EntryTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short description of blog entry.
        /// </summary>
        internal static string EntryTypeShortDescription {
            get {
                return ResourceManager.GetString("EntryTypeShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string Header_Default {
            get {
                return ResourceManager.GetString("Header_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Column.
        /// </summary>
        internal static string Header_FirstColumn {
            get {
                return ResourceManager.GetString("Header_FirstColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Row.
        /// </summary>
        internal static string Header_FirstRow {
            get {
                return ResourceManager.GetString("Header_FirstRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Row And Column.
        /// </summary>
        internal static string Header_FirstRowAndColumn {
            get {
                return ResourceManager.GetString("Header_FirstRowAndColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alt Text.
        /// </summary>
        internal static string Label_AltText {
            get {
                return ResourceManager.GetString("Label_AltText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Border.
        /// </summary>
        internal static string Label_Border {
            get {
                return ResourceManager.GetString("Label_Border", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Columns.
        /// </summary>
        internal static string Label_ColCount {
            get {
                return ResourceManager.GetString("Label_ColCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H Space.
        /// </summary>
        internal static string Label_HSpace {
            get {
                return ResourceManager.GetString("Label_HSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alignment.
        /// </summary>
        internal static string Label_ImgAlignment {
            get {
                return ResourceManager.GetString("Label_ImgAlignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        internal static string Label_ImgHeight {
            get {
                return ResourceManager.GetString("Label_ImgHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string Label_ImgTitle {
            get {
                return ResourceManager.GetString("Label_ImgTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        internal static string Label_ImgWidth {
            get {
                return ResourceManager.GetString("Label_ImgWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link to.
        /// </summary>
        internal static string Label_Link {
            get {
                return ResourceManager.GetString("Label_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Preview.
        /// </summary>
        internal static string Label_NoPreview {
            get {
                return ResourceManager.GetString("Label_NoPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Padding.
        /// </summary>
        internal static string Label_Padding {
            get {
                return ResourceManager.GetString("Label_Padding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rows.
        /// </summary>
        internal static string Label_RowCount {
            get {
                return ResourceManager.GetString("Label_RowCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spacing.
        /// </summary>
        internal static string Label_Spacing {
            get {
                return ResourceManager.GetString("Label_Spacing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alignment.
        /// </summary>
        internal static string Label_TableAlignment {
            get {
                return ResourceManager.GetString("Label_TableAlignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Border.
        /// </summary>
        internal static string Label_TableBorder {
            get {
                return ResourceManager.GetString("Label_TableBorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header.
        /// </summary>
        internal static string Label_TableHeader {
            get {
                return ResourceManager.GetString("Label_TableHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        internal static string Label_TableHeight {
            get {
                return ResourceManager.GetString("Label_TableHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string Label_TableTitle {
            get {
                return ResourceManager.GetString("Label_TableTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        internal static string Label_TableWidth {
            get {
                return ResourceManager.GetString("Label_TableWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        internal static string Label_Text {
            get {
                return ResourceManager.GetString("Label_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL.
        /// </summary>
        internal static string Label_URL {
            get {
                return ResourceManager.GetString("Label_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V Space.
        /// </summary>
        internal static string Label_VSpace {
            get {
                return ResourceManager.GetString("Label_VSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More colors....
        /// </summary>
        internal static string usrHtmlEditor_Background_Header_MoreColors {
            get {
                return ResourceManager.GetString("usrHtmlEditor_Background_Header_MoreColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard colors.
        /// </summary>
        internal static string usrHtmlEditor_Background_Header_StandardColors {
            get {
                return ResourceManager.GetString("usrHtmlEditor_Background_Header_StandardColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme colors.
        /// </summary>
        internal static string usrHtmlEditor_Background_Header_ThemeColors {
            get {
                return ResourceManager.GetString("usrHtmlEditor_Background_Header_ThemeColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic color.
        /// </summary>
        internal static string usrHtmlEditor_Background_Text_AutomaticColor {
            get {
                return ResourceManager.GetString("usrHtmlEditor_Background_Text_AutomaticColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More colors....
        /// </summary>
        internal static string usrHtmlEditor_Foreground_Header_MoreColors {
            get {
                return ResourceManager.GetString("usrHtmlEditor_Foreground_Header_MoreColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard colors.
        /// </summary>
        internal static string usrHtmlEditor_Foreground_Header_StandardColors {
            get {
                return ResourceManager.GetString("usrHtmlEditor_Foreground_Header_StandardColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme colors.
        /// </summary>
        internal static string usrHtmlEditor_Foreground_Header_ThemeColors {
            get {
                return ResourceManager.GetString("usrHtmlEditor_Foreground_Header_ThemeColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic color.
        /// </summary>
        internal static string usrHtmlEditor_Foreground_Text_AutomaticColor {
            get {
                return ResourceManager.GetString("usrHtmlEditor_Foreground_Text_AutomaticColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blog.
        /// </summary>
        internal static string usrHtmlEditor_Header_Blog {
            get {
                return ResourceManager.GetString("usrHtmlEditor_Header_Blog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clipboard.
        /// </summary>
        internal static string usrHtmlEditor_Header_Clipboard {
            get {
                return ResourceManager.GetString("usrHtmlEditor_Header_Clipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font.
        /// </summary>
        internal static string usrHtmlEditor_Header_Font {
            get {
                return ResourceManager.GetString("usrHtmlEditor_Header_Font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert.
        /// </summary>
        internal static string usrHtmlEditor_Header_Insert {
            get {
                return ResourceManager.GetString("usrHtmlEditor_Header_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert table....
        /// </summary>
        internal static string usrHtmlEditor_Header_InsertTable {
            get {
                return ResourceManager.GetString("usrHtmlEditor_Header_InsertTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paragraph.
        /// </summary>
        internal static string usrHtmlEditor_Header_Paragraph {
            get {
                return ResourceManager.GetString("usrHtmlEditor_Header_Paragraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        internal static string usrHtmlEditor_Header_Paste {
            get {
                return ResourceManager.GetString("usrHtmlEditor_Header_Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string usrHtmlEditor_Label_Copy {
            get {
                return ResourceManager.GetString("usrHtmlEditor_Label_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        internal static string usrHtmlEditor_Label_Cut {
            get {
                return ResourceManager.GetString("usrHtmlEditor_Label_Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        internal static string usrHtmlEditor_Label_Paste {
            get {
                return ResourceManager.GetString("usrHtmlEditor_Label_Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table.
        /// </summary>
        internal static string usrHtmlEditor_Label_Table {
            get {
                return ResourceManager.GetString("usrHtmlEditor_Label_Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Hyperlink.
        /// </summary>
        internal static string WinTitle_InsertHyperlink {
            get {
                return ResourceManager.GetString("WinTitle_InsertHyperlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Image.
        /// </summary>
        internal static string WinTitle_InsertImage {
            get {
                return ResourceManager.GetString("WinTitle_InsertImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Table.
        /// </summary>
        internal static string WinTitle_InsertTable {
            get {
                return ResourceManager.GetString("WinTitle_InsertTable", resourceCulture);
            }
        }
    }
}
