//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BodyArchitect.Client.Module.StrengthTraining {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class StrengthTraining : global::System.Configuration.ApplicationSettingsBase {
        
        private static StrengthTraining defaultInstance = ((StrengthTraining)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new StrengthTraining())));
        
        public static StrengthTraining Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FillRepetitionNumberFromPlan {
            get {
                return ((bool)(this["FillRepetitionNumberFromPlan"]));
            }
            set {
                this["FillRepetitionNumberFromPlan"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowExtendedInfoInSets {
            get {
                return ((bool)(this["ShowExtendedInfoInSets"]));
            }
            set {
                this["ShowExtendedInfoInSets"] = value;
            }
        }
    }
}
