using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using BodyArchitect.Model;
using NHibernate;

namespace BodyArchitect.DataAccess.Converter.V4_V5.SupplementsDefinitions
{
    class SupplementsDefinitionStormShockTherapyCycle_WithIncreasingDosageEveryWeek
    {
        private const string Storm = "UNIVERSAL Storm";
        private const string Shock = "UNIVERSAL Shock Therapy";

        public SupplementCycleDefinition Create(IStatelessSession newSession, Profile profile)
        {
            var storm = newSession.Get<Suplement>(new Guid("598a10da-ee36-4706-8abc-aa218b0ac142"));
            var shock = newSession.Get<Suplement>(new Guid("4e9df6c8-9652-4c15-9cc5-a09a33f19c97"));

            var cycleDefinition = new SupplementCycleDefinition();
            cycleDefinition.Profile = profile;
            cycleDefinition.Name = string.Format("Storm z Shock Therapy (zwiększanie dawki)");
            cycleDefinition.Language = "pl";
            cycleDefinition.Profile = profile;
            cycleDefinition.Difficult = TrainingPlanDifficult.Advanced;
            cycleDefinition.CanBeIllegal = false;
            cycleDefinition.Status = PublishStatus.Published;
            cycleDefinition.PublishDate = DateTime.UtcNow;
            cycleDefinition.Purpose = WorkoutPlanPurpose.Mass;
            cycleDefinition.CreationDate = DateTime.UtcNow;
            cycleDefinition.Comment = "Standardowy cykl kreatynowy. Bierzemy dwie porcje kreatyny UNIVERSAL Storm w dni treningowe (najlepiej rano i po treningu - odstęp min 8 godź). A w dni nietreningowe jedna porcja." +
                                      "\r\nShock Therapy przed treningiem w dni treningowe";
            cycleDefinition.Comment = " Bierzemy dwie porcje kreatyny UNIVERSAL Storm w dni treningowe (najlepiej rano i po treningu - odstęp min 8 godź). A w dni nietreningowe jedna porcja." +
                                      "\r\nShock Therapy tylko przed treningiem i zwiększamy co tydzień o pół porcji" +
                                      "\r\nDługość cyklu 6-8 tyg.";
            newSession.Insert(cycleDefinition);

            SupplementCycleWeek trainingWeek = new SupplementCycleWeek();
            cycleDefinition.Weeks.Add(trainingWeek);
            trainingWeek.CycleWeekStart = 1;
            trainingWeek.CycleWeekEnd = 1;
            trainingWeek.Definition = cycleDefinition;
            newSession.Insert(trainingWeek);

            SupplementCycleDosage dosage = new SupplementCycleDosage();
            dosage.Dosage = 1;
            dosage.DosageType = DosageType.Servings;
            dosage.Repetitions = SupplementCycleDayRepetitions.StrengthTrainingDay;
            dosage.Supplement = storm;
            dosage.Name = Storm;
            dosage.TimeType = TimeType.OnEmptyStomach;
            trainingWeek.Dosages.Add(dosage);
            dosage.Week = trainingWeek;
            newSession.Insert(dosage);
            dosage = new SupplementCycleDosage();
            dosage.Dosage = 1;
            dosage.DosageType = DosageType.Servings;
            dosage.Supplement = storm;
            dosage.Name = Storm;
            dosage.Repetitions = SupplementCycleDayRepetitions.StrengthTrainingDay;
            dosage.TimeType = TimeType.AfterWorkout;
            trainingWeek.Dosages.Add(dosage);
            dosage.Week = trainingWeek;
            newSession.Insert(dosage);
            dosage = new SupplementCycleDosage();
            dosage.Dosage = 1;
            dosage.Repetitions = SupplementCycleDayRepetitions.StrengthTrainingDay;
            dosage.DosageType = DosageType.Servings;
            dosage.Supplement = shock;
            dosage.Name = Shock;
            dosage.TimeType = TimeType.BeforeWorkout;
            trainingWeek.Dosages.Add(dosage);
            dosage.Week = trainingWeek;
            newSession.Insert(dosage);

            SupplementCycleWeek nonTrainingWeek = new SupplementCycleWeek();
            nonTrainingWeek.Name = "Non training week";
            cycleDefinition.Weeks.Add(nonTrainingWeek);
            nonTrainingWeek.CycleWeekStart = 1;
            nonTrainingWeek.CycleWeekEnd = 1;
            nonTrainingWeek.Definition = cycleDefinition;
            newSession.Insert(nonTrainingWeek);
            dosage = new SupplementCycleDosage();
            dosage.Repetitions = SupplementCycleDayRepetitions.NonTrainingDay;
            dosage.Dosage = 1;
            dosage.DosageType = DosageType.Servings;
            dosage.Supplement = storm;
            dosage.Name = Storm;
            dosage.TimeType = TimeType.OnEmptyStomach;
            nonTrainingWeek.Dosages.Add(dosage);
            dosage.Week = nonTrainingWeek;
            newSession.Insert(dosage);
            dosage = new SupplementCycleDosage();
            dosage.Dosage = 1;
            dosage.DosageType = DosageType.Servings;
            dosage.Repetitions = SupplementCycleDayRepetitions.NonTrainingDay;
            dosage.Name = Storm;
            dosage.Supplement = storm;
            dosage.TimeType = TimeType.NotSet;
            nonTrainingWeek.Dosages.Add(dosage);
            dosage.Week = nonTrainingWeek;
            newSession.Insert(dosage);

            //week 2
            trainingWeek = new SupplementCycleWeek();
            trainingWeek.Name = "Training week";
            cycleDefinition.Weeks.Add(trainingWeek);
            trainingWeek.CycleWeekStart = 2;
            trainingWeek.CycleWeekEnd = 2;
            trainingWeek.Definition = cycleDefinition;
            newSession.Insert(trainingWeek);

            dosage = new SupplementCycleDosage();
            dosage.Dosage = 1;
            dosage.DosageType = DosageType.Servings;
            dosage.Repetitions = SupplementCycleDayRepetitions.StrengthTrainingDay;
            dosage.Supplement = storm;
            dosage.Name = Storm;
            dosage.TimeType = TimeType.OnEmptyStomach;
            trainingWeek.Dosages.Add(dosage);
            dosage.Week = trainingWeek;
            newSession.Insert(dosage);
            dosage = new SupplementCycleDosage();
            dosage.Dosage = 1;
            dosage.DosageType = DosageType.Servings;
            dosage.Supplement = storm;
            dosage.Repetitions = SupplementCycleDayRepetitions.StrengthTrainingDay;
            dosage.Name = Storm;
            dosage.TimeType = TimeType.AfterWorkout;
            trainingWeek.Dosages.Add(dosage);
            dosage.Week = trainingWeek;
            newSession.Insert(dosage);
            dosage = new SupplementCycleDosage();
            dosage.Dosage = 1.5M;
            dosage.DosageType = DosageType.Servings;
            dosage.Repetitions = SupplementCycleDayRepetitions.StrengthTrainingDay;
            dosage.Supplement = shock;
            dosage.Name = Shock;
            dosage.TimeType = TimeType.BeforeWorkout;
            trainingWeek.Dosages.Add(dosage);
            dosage.Week = trainingWeek;
            newSession.Insert(dosage);

            nonTrainingWeek = new SupplementCycleWeek();
            nonTrainingWeek.CycleWeekStart = 2;
            nonTrainingWeek.CycleWeekEnd = 2;
            nonTrainingWeek.Name = "Non training week";
            cycleDefinition.Weeks.Add(nonTrainingWeek);
            nonTrainingWeek.Definition = cycleDefinition;
            newSession.Insert(nonTrainingWeek);
            dosage = new SupplementCycleDosage();
            dosage.Dosage = 1;
            dosage.DosageType = DosageType.Servings;
            dosage.Repetitions = SupplementCycleDayRepetitions.NonTrainingDay;
            dosage.Supplement = storm;
            dosage.Name = Storm;
            dosage.TimeType = TimeType.OnEmptyStomach;
            nonTrainingWeek.Dosages.Add(dosage);
            dosage.Week = nonTrainingWeek;
            newSession.Insert(dosage);
            dosage = new SupplementCycleDosage();
            dosage.Dosage = 1;
            dosage.DosageType = DosageType.Servings;
            dosage.Name = Storm;
            dosage.Supplement = storm;
            dosage.Repetitions = SupplementCycleDayRepetitions.NonTrainingDay;
            dosage.TimeType = TimeType.NotSet;
            nonTrainingWeek.Dosages.Add(dosage);
            dosage.Week = nonTrainingWeek;
            newSession.Insert(dosage);

            //week 3
            trainingWeek = new SupplementCycleWeek();
            trainingWeek.Name = "Training week";
            cycleDefinition.Weeks.Add(trainingWeek);
            trainingWeek.CycleWeekStart = 3;
            trainingWeek.CycleWeekEnd = 3;
            trainingWeek.Definition = cycleDefinition;
            newSession.Insert(trainingWeek);
            dosage = new SupplementCycleDosage();
            dosage.Dosage = 1;
            dosage.Repetitions = SupplementCycleDayRepetitions.StrengthTrainingDay;
            dosage.DosageType = DosageType.Servings;
            dosage.Supplement = storm;
            dosage.Name = Storm;
            dosage.TimeType = TimeType.OnEmptyStomach;
            trainingWeek.Dosages.Add(dosage);
            dosage.Week = trainingWeek;
            newSession.Insert(dosage);
            dosage = new SupplementCycleDosage();
            dosage.Dosage = 1;
            dosage.DosageType = DosageType.Servings;
            dosage.Repetitions = SupplementCycleDayRepetitions.StrengthTrainingDay;
            dosage.Supplement = storm;
            dosage.Name = Storm;
            dosage.TimeType = TimeType.AfterWorkout;
            trainingWeek.Dosages.Add(dosage);
            dosage.Week = trainingWeek;
            newSession.Insert(dosage);
            dosage = new SupplementCycleDosage();
            dosage.Repetitions = SupplementCycleDayRepetitions.StrengthTrainingDay;
            dosage.Dosage = 2;
            dosage.DosageType = DosageType.Servings;
            dosage.Supplement = shock;
            dosage.Name = Shock;
            dosage.TimeType = TimeType.BeforeWorkout;
            trainingWeek.Dosages.Add(dosage);
            dosage.Week = trainingWeek;
            newSession.Insert(dosage);

            nonTrainingWeek = new SupplementCycleWeek();
            nonTrainingWeek.CycleWeekStart = 3;
            nonTrainingWeek.CycleWeekEnd = 3;
            nonTrainingWeek.Name = "Non training week";
            cycleDefinition.Weeks.Add(nonTrainingWeek);
            nonTrainingWeek.Definition = cycleDefinition;
            newSession.Insert(nonTrainingWeek);
            dosage = new SupplementCycleDosage();
            dosage.Dosage = 1;
            dosage.Repetitions = SupplementCycleDayRepetitions.NonTrainingDay;
            dosage.DosageType = DosageType.Servings;
            dosage.Supplement = storm;
            dosage.Name = Storm;
            dosage.TimeType = TimeType.OnEmptyStomach;
            nonTrainingWeek.Dosages.Add(dosage);
            dosage.Week = nonTrainingWeek;
            newSession.Insert(dosage);
            dosage = new SupplementCycleDosage();
            dosage.Dosage = 1;
            dosage.DosageType = DosageType.Servings;
            dosage.Repetitions = SupplementCycleDayRepetitions.NonTrainingDay;
            dosage.Supplement = storm;
            dosage.Name = Storm;
            dosage.TimeType = TimeType.NotSet;
            nonTrainingWeek.Dosages.Add(dosage);
            dosage.Week = nonTrainingWeek;
            newSession.Insert(dosage);

            //week 4
            trainingWeek = new SupplementCycleWeek();
            trainingWeek.Name = "Training week";
            cycleDefinition.Weeks.Add(trainingWeek);
            trainingWeek.CycleWeekStart = 4;
            trainingWeek.CycleWeekEnd = 4;
            trainingWeek.Definition = cycleDefinition;
            newSession.Insert(trainingWeek);
            dosage = new SupplementCycleDosage();
            dosage.Dosage = 1;
            dosage.DosageType = DosageType.Servings;
            dosage.Supplement = storm;
            dosage.Name = Storm;
            dosage.Repetitions = SupplementCycleDayRepetitions.StrengthTrainingDay;
            dosage.TimeType = TimeType.OnEmptyStomach;
            trainingWeek.Dosages.Add(dosage);
            dosage.Week = trainingWeek;
            newSession.Insert(dosage);
            dosage = new SupplementCycleDosage();
            dosage.Dosage = 1;
            dosage.DosageType = DosageType.Servings;
            dosage.Supplement = storm;
            dosage.Repetitions = SupplementCycleDayRepetitions.StrengthTrainingDay;
            dosage.Name = Storm;
            dosage.TimeType = TimeType.AfterWorkout;
            trainingWeek.Dosages.Add(dosage);
            dosage.Week = trainingWeek;
            newSession.Insert(dosage);
            dosage = new SupplementCycleDosage();
            dosage.Dosage = 2.5M;
            dosage.DosageType = DosageType.Servings;
            dosage.Repetitions = SupplementCycleDayRepetitions.StrengthTrainingDay;
            dosage.Supplement = shock;
            dosage.Name = Shock;
            dosage.TimeType = TimeType.BeforeWorkout;
            trainingWeek.Dosages.Add(dosage);
            dosage.Week = trainingWeek;
            newSession.Insert(dosage);

            nonTrainingWeek = new SupplementCycleWeek();
            nonTrainingWeek.CycleWeekStart = 4;
            nonTrainingWeek.CycleWeekEnd = 4;
            nonTrainingWeek.Name = "Non training week";
            cycleDefinition.Weeks.Add(nonTrainingWeek);
            nonTrainingWeek.Definition = cycleDefinition;
            newSession.Insert(nonTrainingWeek);
            dosage = new SupplementCycleDosage();
            dosage.Dosage = 1;
            dosage.DosageType = DosageType.Servings;
            dosage.Repetitions = SupplementCycleDayRepetitions.NonTrainingDay;
            dosage.Supplement = storm;
            dosage.Name = Storm;
            dosage.TimeType = TimeType.OnEmptyStomach;
            nonTrainingWeek.Dosages.Add(dosage);
            dosage.Week = nonTrainingWeek;
            newSession.Insert(dosage);
            dosage = new SupplementCycleDosage();
            dosage.Dosage = 1;
            dosage.DosageType = DosageType.Servings;
            dosage.Repetitions = SupplementCycleDayRepetitions.NonTrainingDay;
            dosage.Supplement = storm;
            dosage.Name = Storm;
            dosage.TimeType = TimeType.NotSet;
            nonTrainingWeek.Dosages.Add(dosage);
            dosage.Week = nonTrainingWeek;
            newSession.Insert(dosage);

            //week 5
            trainingWeek = new SupplementCycleWeek();
            trainingWeek.Name = "Training week";
            cycleDefinition.Weeks.Add(trainingWeek);
            trainingWeek.CycleWeekStart = 5;
            trainingWeek.CycleWeekEnd = 5;
            trainingWeek.Definition = cycleDefinition;
            newSession.Insert(trainingWeek);
            dosage = new SupplementCycleDosage();
            dosage.Dosage = 1;
            dosage.DosageType = DosageType.Servings;
            dosage.Supplement = storm;
            dosage.Name = Storm;
            dosage.TimeType = TimeType.OnEmptyStomach;
            dosage.Repetitions = SupplementCycleDayRepetitions.StrengthTrainingDay;
            trainingWeek.Dosages.Add(dosage);
            dosage.Week = trainingWeek;
            newSession.Insert(dosage);
            dosage = new SupplementCycleDosage();
            dosage.Dosage = 1;
            dosage.DosageType = DosageType.Servings;
            dosage.Supplement = storm;
            dosage.Name = Storm;
            dosage.Repetitions = SupplementCycleDayRepetitions.StrengthTrainingDay;
            dosage.TimeType = TimeType.AfterWorkout;
            trainingWeek.Dosages.Add(dosage);
            dosage.Week = trainingWeek;
            newSession.Insert(dosage);
            dosage = new SupplementCycleDosage();
            dosage.Dosage = 3;
            dosage.Repetitions = SupplementCycleDayRepetitions.StrengthTrainingDay;
            dosage.DosageType = DosageType.Servings;
            dosage.Supplement = shock;
            dosage.Name = Shock;
            dosage.TimeType = TimeType.BeforeWorkout;
            trainingWeek.Dosages.Add(dosage);
            dosage.Week = trainingWeek;
            newSession.Insert(dosage);

            nonTrainingWeek = new SupplementCycleWeek();
            nonTrainingWeek.CycleWeekStart = 5;
            nonTrainingWeek.CycleWeekEnd = 5;
            nonTrainingWeek.Name = "Non training week";
            cycleDefinition.Weeks.Add(nonTrainingWeek);
            nonTrainingWeek.Definition = cycleDefinition;
            newSession.Insert(nonTrainingWeek);
            dosage = new SupplementCycleDosage();
            dosage.Dosage = 1;
            dosage.DosageType = DosageType.Servings;
            dosage.Repetitions = SupplementCycleDayRepetitions.NonTrainingDay;
            dosage.Supplement = storm;
            dosage.Name = Storm;
            dosage.TimeType = TimeType.OnEmptyStomach;
            nonTrainingWeek.Dosages.Add(dosage);
            dosage.Week = nonTrainingWeek;
            newSession.Insert(dosage);
            dosage = new SupplementCycleDosage();
            dosage.Dosage = 1;
            dosage.DosageType = DosageType.Servings;
            dosage.Repetitions = SupplementCycleDayRepetitions.NonTrainingDay;
            dosage.Name = Storm;
            dosage.Supplement = storm;
            dosage.TimeType = TimeType.NotSet;
            nonTrainingWeek.Dosages.Add(dosage);
            dosage.Week = nonTrainingWeek;
            newSession.Insert(dosage);

            //week 6
            trainingWeek = new SupplementCycleWeek();
            trainingWeek.Name = "Training week";
            cycleDefinition.Weeks.Add(trainingWeek);
            trainingWeek.CycleWeekStart = 6;
            trainingWeek.CycleWeekEnd = 6;
            trainingWeek.Definition = cycleDefinition;
            newSession.Insert(trainingWeek);
            dosage = new SupplementCycleDosage();
            dosage.Dosage = 1;
            dosage.Repetitions = SupplementCycleDayRepetitions.StrengthTrainingDay;
            dosage.DosageType = DosageType.Servings;
            dosage.Supplement = storm;
            dosage.Name = Storm;
            dosage.TimeType = TimeType.OnEmptyStomach;
            trainingWeek.Dosages.Add(dosage);
            dosage.Week = trainingWeek;
            newSession.Insert(dosage);
            dosage = new SupplementCycleDosage();
            dosage.Dosage = 1;
            dosage.DosageType = DosageType.Servings;
            dosage.Supplement = storm;
            dosage.Repetitions = SupplementCycleDayRepetitions.StrengthTrainingDay;
            dosage.Name = Storm;
            dosage.TimeType = TimeType.AfterWorkout;
            trainingWeek.Dosages.Add(dosage);
            dosage.Week = trainingWeek;
            newSession.Insert(dosage);
            dosage = new SupplementCycleDosage();
            dosage.Repetitions = SupplementCycleDayRepetitions.StrengthTrainingDay;
            dosage.Dosage = 3.5M;
            dosage.DosageType = DosageType.Servings;
            dosage.Supplement = shock;
            dosage.Name = Shock;
            dosage.TimeType = TimeType.BeforeWorkout;
            trainingWeek.Dosages.Add(dosage);
            dosage.Week = trainingWeek;
            newSession.Insert(dosage);

            nonTrainingWeek = new SupplementCycleWeek();
            nonTrainingWeek.CycleWeekStart = 6;
            nonTrainingWeek.CycleWeekEnd = 6;
            nonTrainingWeek.Name = "Non training week";
            cycleDefinition.Weeks.Add(nonTrainingWeek);
            nonTrainingWeek.Definition = cycleDefinition;
            newSession.Insert(nonTrainingWeek);
            dosage = new SupplementCycleDosage();
            dosage.Dosage = 1;
            dosage.DosageType = DosageType.Servings;
            dosage.Supplement = storm;
            dosage.Repetitions = SupplementCycleDayRepetitions.NonTrainingDay;
            dosage.Name = Storm;
            dosage.TimeType = TimeType.OnEmptyStomach;
            nonTrainingWeek.Dosages.Add(dosage);
            dosage.Week = nonTrainingWeek;
            newSession.Insert(dosage);
            dosage = new SupplementCycleDosage();
            dosage.Dosage = 1;
            dosage.DosageType = DosageType.Servings;
            dosage.Repetitions = SupplementCycleDayRepetitions.NonTrainingDay;
            dosage.Name = Storm;
            dosage.Supplement = storm;
            dosage.TimeType = TimeType.NotSet;
            nonTrainingWeek.Dosages.Add(dosage);
            dosage.Week = nonTrainingWeek;
            newSession.Insert(dosage);

            return cycleDefinition;
        }

    }
}
