//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BodyArchitect.Service.V2.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LocalizedStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizedStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BodyArchitect.Service.V2.Localization.LocalizedStrings", typeof(LocalizedStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At {1} user {0} has accepted an invitation. Now he is in your friend&apos;s circle.
        ///
        ///He wrote „{2}”..
        /// </summary>
        public static string AcceptInvitationEMailMessage {
            get {
                return ResourceManager.GetString("AcceptInvitationEMailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} has accepted an invitation..
        /// </summary>
        public static string AcceptInvitationEMailSubject {
            get {
                return ResourceManager.GetString("AcceptInvitationEMailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At {0} user {1} has commented your training day {2}.
        ///
        ///He wrote „{3}”..
        /// </summary>
        public static string AddTrainingDayCommentEMailMessage {
            get {
                return ResourceManager.GetString("AddTrainingDayCommentEMailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {1} has commented your training day {2}..
        /// </summary>
        public static string AddTrainingDayCommentEMailSubject {
            get {
                return ResourceManager.GetString("AddTrainingDayCommentEMailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At {0} you have created a profile in BodyArchitect application.
        ///
        ///
        ///
        ///Your user name: {1}..
        /// </summary>
        public static string CreateProfileEMailMessage {
            get {
                return ResourceManager.GetString("CreateProfileEMailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At {0} you have created a profile in BodyArchitect application.
        ///
        ///
        ///
        ///Your user name: {1}.
        ///
        ///You must click this link to activate your account:
        ///{2}.
        /// </summary>
        public static string CreateProfileEMailMessage_ActivationMode {
            get {
                return ResourceManager.GetString("CreateProfileEMailMessage_ActivationMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the BodyArchitect.
        /// </summary>
        public static string CreateProfileEMailSubject {
            get {
                return ResourceManager.GetString("CreateProfileEMailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} has deleted his profile..
        /// </summary>
        public static string FavoriteProfileDeleted_Content {
            get {
                return ResourceManager.GetString("FavoriteProfileDeleted_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User has deleted his profile..
        /// </summary>
        public static string FavoriteProfileDeleted_Topic {
            get {
                return ResourceManager.GetString("FavoriteProfileDeleted_Topic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At {2} user {0} changed his calendar on {1}.
        ///
        ///Records:
        ///{3}.
        /// </summary>
        public static string FollowersTrainingDayChangedEMailMessage {
            get {
                return ResourceManager.GetString("FollowersTrainingDayChangedEMailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} changed his calendar on {1}..
        /// </summary>
        public static string FollowersTrainingDayChangedEMailSubject {
            get {
                return ResourceManager.GetString("FollowersTrainingDayChangedEMailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} has deleted his profile..
        /// </summary>
        public static string FriendProfileDeleted_Content {
            get {
                return ResourceManager.GetString("FriendProfileDeleted_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User has deleted his profile..
        /// </summary>
        public static string FriendProfileDeleted_Topic {
            get {
                return ResourceManager.GetString("FriendProfileDeleted_Topic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At {2} user {0} changed his calendar on {1}.
        ///
        ///Records:
        ///{3}.
        /// </summary>
        public static string FriendsTrainingDayChangedEMailMessage {
            get {
                return ResourceManager.GetString("FriendsTrainingDayChangedEMailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} changed his calendar on {1}..
        /// </summary>
        public static string FriendsTrainingDayChangedEMailSubject {
            get {
                return ResourceManager.GetString("FriendsTrainingDayChangedEMailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At {1} user {0} has invite you to his circle of friends.
        ///
        ///He wrote „{2}”.
        /// </summary>
        public static string InviteFriendEMailMessage {
            get {
                return ResourceManager.GetString("InviteFriendEMailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} has invite you to his circle of friends..
        /// </summary>
        public static string InviteFriendEMailSubject {
            get {
                return ResourceManager.GetString("InviteFriendEMailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the best fitness application. You can use it as your workout log, workout plans database or to share with other users logs, plans and more... Be creative and use this application every day..
        /// </summary>
        public static string ProfileCreated_Content {
            get {
                return ResourceManager.GetString("ProfileCreated_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the BodyArchitect!.
        /// </summary>
        public static string ProfileCreated_Topic {
            get {
                return ResourceManager.GetString("ProfileCreated_Topic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At {1} user {0} has rejected friendship with you.
        ///
        ///He wrote „{2}”..
        /// </summary>
        public static string RejectFriendshipEmailMessage {
            get {
                return ResourceManager.GetString("RejectFriendshipEmailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} has rejected friendhips with you..
        /// </summary>
        public static string RejectFriendshipEmailSubject {
            get {
                return ResourceManager.GetString("RejectFriendshipEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At {1} user {0} has rejected invitation from you.
        ///
        ///He wrote „{2}”.
        /// </summary>
        public static string RejectInvitationEmailMessage {
            get {
                return ResourceManager.GetString("RejectInvitationEmailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} has rejected invitation from you..
        /// </summary>
        public static string RejectInvitationEmailSubject {
            get {
                return ResourceManager.GetString("RejectInvitationEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has birthday at {1}.
        /// </summary>
        public static string ReminderBirthday {
            get {
                return ResourceManager.GetString("ReminderBirthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At {0} you have measurements planned..
        /// </summary>
        public static string ReminderMeasurements {
            get {
                return ResourceManager.GetString("ReminderMeasurements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At {0} you have {1} activity..
        /// </summary>
        public static string ReminderScheduleEntry {
            get {
                return ResourceManager.GetString("ReminderScheduleEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At {0} you have strength training planned..
        /// </summary>
        public static string ReminderStrengthTraining {
            get {
                return ResourceManager.GetString("ReminderStrengthTraining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At {0} you have supplements planned..
        /// </summary>
        public static string ReminderSupplements {
            get {
                return ResourceManager.GetString("ReminderSupplements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At {0} password for your account has been restored.
        ///
        ///The new password is: {1}.
        /// </summary>
        public static string RestorePasswordEmailMessage {
            get {
                return ResourceManager.GetString("RestorePasswordEmailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BodyArchitect - new password.
        /// </summary>
        public static string RestorePasswordEmailSubject {
            get {
                return ResourceManager.GetString("RestorePasswordEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplement cycle: {0}.
        /// </summary>
        public static string SupplementDefinitionEntry_ReminderName {
            get {
                return ResourceManager.GetString("SupplementDefinitionEntry_ReminderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At {0} user {1} has voted on your {2}. This user gave {3} stars..
        /// </summary>
        public static string VoteEMailMessage {
            get {
                return ResourceManager.GetString("VoteEMailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {1} has voted on your {2}..
        /// </summary>
        public static string VoteEMailSubject {
            get {
                return ResourceManager.GetString("VoteEMailSubject", resourceCulture);
            }
        }
    }
}
