//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BodyArchitect.Service.V2.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SupplementsStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SupplementsStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BodyArchitect.Service.V2.Localization.SupplementsStrings", typeof(SupplementsStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creatine - malate.
        /// </summary>
        internal static string _094A2EC2_D81C_4B41_B8F5_2A2DEB4BFF2F_Name {
            get {
                return ResourceManager.GetString("094A2EC2-D81C-4B41-B8F5-2A2DEB4BFF2F_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string _094A2EC2_D81C_4B41_B8F5_2A2DEB4BFF2F_Url {
            get {
                return ResourceManager.GetString("094A2EC2-D81C-4B41-B8F5-2A2DEB4BFF2F_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carbo.
        /// </summary>
        internal static string _0BB3367F_509A_4CD2_9BB0_5CE9740A2DF8_Name {
            get {
                return ResourceManager.GetString("0BB3367F-509A-4CD2-9BB0-5CE9740A2DF8_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string _0BB3367F_509A_4CD2_9BB0_5CE9740A2DF8_Url {
            get {
                return ResourceManager.GetString("0BB3367F-509A-4CD2-9BB0-5CE9740A2DF8_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joins regeneration.
        /// </summary>
        internal static string _1062465F_365A_432E_BAEB_6A7ADA1A43EC_Name {
            get {
                return ResourceManager.GetString("1062465F-365A-432E-BAEB-6A7ADA1A43EC_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string _1062465F_365A_432E_BAEB_6A7ADA1A43EC_Url {
            get {
                return ResourceManager.GetString("1062465F-365A-432E-BAEB-6A7ADA1A43EC_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taurine.
        /// </summary>
        internal static string _13826022_8F20_4210_BF5E_0AA963CFC194_Name {
            get {
                return ResourceManager.GetString("13826022-8F20-4210-BF5E-0AA963CFC194_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string _13826022_8F20_4210_BF5E_0AA963CFC194_Url {
            get {
                return ResourceManager.GetString("13826022-8F20-4210-BF5E-0AA963CFC194_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLA.
        /// </summary>
        internal static string _1C056347_996B_444A_98B9_4D00B1AF2663_Name {
            get {
                return ResourceManager.GetString("1C056347-996B-444A-98B9-4D00B1AF2663_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string _1C056347_996B_444A_98B9_4D00B1AF2663_Url {
            get {
                return ResourceManager.GetString("1C056347-996B-444A-98B9-4D00B1AF2663_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glutamine.
        /// </summary>
        internal static string _1EE3FA0F_0835_4462_B8F7_1C036EFD5097_Name {
            get {
                return ResourceManager.GetString("1EE3FA0F-0835-4462-B8F7-1C036EFD5097_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string _1EE3FA0F_0835_4462_B8F7_1C036EFD5097_Url {
            get {
                return ResourceManager.GetString("1EE3FA0F-0835-4462-B8F7-1C036EFD5097_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gainer.
        /// </summary>
        internal static string _1F052451_42AA_4C8D_8FD8_E099C5237B1A_Name {
            get {
                return ResourceManager.GetString("1F052451-42AA-4C8D-8FD8-E099C5237B1A_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string _1F052451_42AA_4C8D_8FD8_E099C5237B1A_Url {
            get {
                return ResourceManager.GetString("1F052451-42AA-4C8D-8FD8-E099C5237B1A_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulk.
        /// </summary>
        internal static string _20F62CA7_B5CC_4765_B17E_B807F72C6234_Name {
            get {
                return ResourceManager.GetString("20F62CA7-B5CC-4765-B17E-B807F72C6234_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string _20F62CA7_B5CC_4765_B17E_B807F72C6234_Url {
            get {
                return ResourceManager.GetString("20F62CA7-B5CC-4765-B17E-B807F72C6234_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creatine - monohydrate.
        /// </summary>
        internal static string _296004CF_4F0D_4FA9_8897_2349F3F411D3_Name {
            get {
                return ResourceManager.GetString("296004CF-4F0D-4FA9-8897-2349F3F411D3_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string _296004CF_4F0D_4FA9_8897_2349F3F411D3_Url {
            get {
                return ResourceManager.GetString("296004CF-4F0D-4FA9-8897-2349F3F411D3_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BCAA.
        /// </summary>
        internal static string _34A141F4_3448_4552_9AB7_1B2537F7DA1A_Name {
            get {
                return ResourceManager.GetString("34A141F4-3448-4552-9AB7-1B2537F7DA1A_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string _34A141F4_3448_4552_9AB7_1B2537F7DA1A_Url {
            get {
                return ResourceManager.GetString("34A141F4-3448-4552-9AB7-1B2537F7DA1A_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whey.
        /// </summary>
        internal static string _3B2BF26F_5310_4148_8E4E_3C0431C0FA75_Name {
            get {
                return ResourceManager.GetString("3B2BF26F-5310-4148-8E4E-3C0431C0FA75_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string _3B2BF26F_5310_4148_8E4E_3C0431C0FA75_Url {
            get {
                return ResourceManager.GetString("3B2BF26F-5310-4148-8E4E-3C0431C0FA75_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izotonic.
        /// </summary>
        internal static string _4B1DF63B_24AF_4B98_95AE_70407BC4193E_Name {
            get {
                return ResourceManager.GetString("4B1DF63B-24AF-4B98-95AE-70407BC4193E_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string _4B1DF63B_24AF_4B98_95AE_70407BC4193E_Url {
            get {
                return ResourceManager.GetString("4B1DF63B-24AF-4B98-95AE-70407BC4193E_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre-Workout Nutrition.
        /// </summary>
        internal static string _4E9DF6C8_9652_4C15_9CC5_A09A33F19C97_Name {
            get {
                return ResourceManager.GetString("4E9DF6C8-9652-4C15-9CC5-A09A33F19C97_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string _4E9DF6C8_9652_4C15_9CC5_A09A33F19C97_Url {
            get {
                return ResourceManager.GetString("4E9DF6C8-9652-4C15-9CC5-A09A33F19C97_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creatine - stack.
        /// </summary>
        internal static string _598A10DA_EE36_4706_8ABC_AA218B0AC142_Name {
            get {
                return ResourceManager.GetString("598A10DA-EE36-4706-8ABC-AA218B0AC142_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string _598A10DA_EE36_4706_8ABC_AA218B0AC142_Url {
            get {
                return ResourceManager.GetString("598A10DA-EE36-4706-8ABC-AA218B0AC142_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caffeine.
        /// </summary>
        internal static string _677EBCC7_8113_4B81_9061_54D8CC07C7D2_Name {
            get {
                return ResourceManager.GetString("677EBCC7-8113-4B81-9061-54D8CC07C7D2_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string _677EBCC7_8113_4B81_9061_54D8CC07C7D2_Url {
            get {
                return ResourceManager.GetString("677EBCC7-8113-4B81-9061-54D8CC07C7D2_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fat burner.
        /// </summary>
        internal static string _6924B01A_AE6B_4056_BEDA_7EDAE5F5B1C4_Name {
            get {
                return ResourceManager.GetString("6924B01A-AE6B-4056-BEDA-7EDAE5F5B1C4_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string _6924B01A_AE6B_4056_BEDA_7EDAE5F5B1C4_Url {
            get {
                return ResourceManager.GetString("6924B01A-AE6B-4056-BEDA-7EDAE5F5B1C4_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leucine.
        /// </summary>
        internal static string _6930E4C1_18E9_482E_BAF2_90697F4AE75E_Name {
            get {
                return ResourceManager.GetString("6930E4C1-18E9-482E-BAF2-90697F4AE75E_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string _6930E4C1_18E9_482E_BAF2_90697F4AE75E_Url {
            get {
                return ResourceManager.GetString("6930E4C1-18E9-482E-BAF2-90697F4AE75E_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L-Arginine.
        /// </summary>
        internal static string _6F1E5C88_4BB2_4E61_BACE_F05BF4442AEB_Name {
            get {
                return ResourceManager.GetString("6F1E5C88-4BB2-4E61-BACE-F05BF4442AEB_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string _6F1E5C88_4BB2_4E61_BACE_F05BF4442AEB_Url {
            get {
                return ResourceManager.GetString("6F1E5C88-4BB2-4E61-BACE-F05BF4442AEB_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dextrose.
        /// </summary>
        internal static string _7281644E_6231_435A_A9F3_2E0D07411578_Name {
            get {
                return ResourceManager.GetString("7281644E-6231-435A-A9F3-2E0D07411578_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string _7281644E_6231_435A_A9F3_2E0D07411578_Url {
            get {
                return ResourceManager.GetString("7281644E-6231-435A-A9F3-2E0D07411578_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ribose.
        /// </summary>
        internal static string _85BECB6E_6469_48FC_8249_3BC283ADEF4E_Name {
            get {
                return ResourceManager.GetString("85BECB6E-6469-48FC-8249-3BC283ADEF4E_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string _85BECB6E_6469_48FC_8249_3BC283ADEF4E_Url {
            get {
                return ResourceManager.GetString("85BECB6E-6469-48FC-8249-3BC283ADEF4E_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vitamins.
        /// </summary>
        internal static string _9800EB48_DECF_4F1B_A9B2_0EC1BEAEF70C_Name {
            get {
                return ResourceManager.GetString("9800EB48-DECF-4F1B-A9B2-0EC1BEAEF70C_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string _9800EB48_DECF_4F1B_A9B2_0EC1BEAEF70C_Url {
            get {
                return ResourceManager.GetString("9800EB48-DECF-4F1B-A9B2-0EC1BEAEF70C_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booster - NO.
        /// </summary>
        internal static string _98A601E6_7637_431D_ABDD_2EB165875D30_Name {
            get {
                return ResourceManager.GetString("98A601E6-7637-431D-ABDD-2EB165875D30_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string _98A601E6_7637_431D_ABDD_2EB165875D30_Url {
            get {
                return ResourceManager.GetString("98A601E6-7637-431D-ABDD-2EB165875D30_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZMA.
        /// </summary>
        internal static string A1D6A2FC_3FC1_4EF8_B0C3_E591E553E8EA_Name {
            get {
                return ResourceManager.GetString("A1D6A2FC-3FC1-4EF8-B0C3-E591E553E8EA_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string A1D6A2FC_3FC1_4EF8_B0C3_E591E553E8EA_Url {
            get {
                return ResourceManager.GetString("A1D6A2FC-3FC1-4EF8-B0C3-E591E553E8EA_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Growth hormone.
        /// </summary>
        internal static string B17BAD16_553E_4107_B06E_197F5DF7ACF3_Name {
            get {
                return ResourceManager.GetString("B17BAD16-553E-4107-B06E-197F5DF7ACF3_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string B17BAD16_553E_4107_B06E_197F5DF7ACF3_Url {
            get {
                return ResourceManager.GetString("B17BAD16-553E-4107-B06E-197F5DF7ACF3_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HMB.
        /// </summary>
        internal static string C5660BD4_77EC_465B_A752_5D808662078E_Name {
            get {
                return ResourceManager.GetString("C5660BD4-77EC-465B-A752-5D808662078E_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string C5660BD4_77EC_465B_A752_5D808662078E_Url {
            get {
                return ResourceManager.GetString("C5660BD4-77EC-465B-A752-5D808662078E_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tribulus.
        /// </summary>
        internal static string CFE109F9_B382_41D2_AB77_B0F5825B6744_Name {
            get {
                return ResourceManager.GetString("CFE109F9-B382-41D2-AB77-B0F5825B6744_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CFE109F9_B382_41D2_AB77_B0F5825B6744_Url {
            get {
                return ResourceManager.GetString("CFE109F9-B382-41D2-AB77-B0F5825B6744_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beta-Alanine.
        /// </summary>
        internal static string D19B1D8D_872D_42E8_8737_55CCB9B958B2_Name {
            get {
                return ResourceManager.GetString("D19B1D8D-872D-42E8-8737-55CCB9B958B2_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string D19B1D8D_872D_42E8_8737_55CCB9B958B2_Url {
            get {
                return ResourceManager.GetString("D19B1D8D-872D-42E8-8737-55CCB9B958B2_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prohormone.
        /// </summary>
        internal static string D8F8FD0D_31E0_4763_9F1E_ED5AE49DFBD8_Name {
            get {
                return ResourceManager.GetString("D8F8FD0D-31E0-4763-9F1E-ED5AE49DFBD8_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string D8F8FD0D_31E0_4763_9F1E_ED5AE49DFBD8_Url {
            get {
                return ResourceManager.GetString("D8F8FD0D-31E0-4763-9F1E-ED5AE49DFBD8_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booster - Testosterone.
        /// </summary>
        internal static string E2C2CEC8_F84F_42C4_A338_F0B13FF10323_Name {
            get {
                return ResourceManager.GetString("E2C2CEC8-F84F-42C4-A338-F0B13FF10323_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string E2C2CEC8_F84F_42C4_A338_F0B13FF10323_Url {
            get {
                return ResourceManager.GetString("E2C2CEC8-F84F-42C4-A338-F0B13FF10323_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amino acid.
        /// </summary>
        internal static string E6BB4CF7_60B2_46A4_9E83_252E386C6F2B_Name {
            get {
                return ResourceManager.GetString("E6BB4CF7-60B2-46A4-9E83-252E386C6F2B_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string E6BB4CF7_60B2_46A4_9E83_252E386C6F2B_Url {
            get {
                return ResourceManager.GetString("E6BB4CF7-60B2-46A4-9E83-252E386C6F2B_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carnitine.
        /// </summary>
        internal static string ED696310_1AE1_4E3A_99DA_78B05A21F73A_Name {
            get {
                return ResourceManager.GetString("ED696310-1AE1-4E3A-99DA-78B05A21F73A_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ED696310_1AE1_4E3A_99DA_78B05A21F73A_Url {
            get {
                return ResourceManager.GetString("ED696310-1AE1-4E3A-99DA-78B05A21F73A_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steroid.
        /// </summary>
        internal static string F099FF98_BB78_4E99_AFA3_EE0355974CD9_Name {
            get {
                return ResourceManager.GetString("F099FF98-BB78-4E99-AFA3-EE0355974CD9_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string F099FF98_BB78_4E99_AFA3_EE0355974CD9_Url {
            get {
                return ResourceManager.GetString("F099FF98-BB78-4E99-AFA3-EE0355974CD9_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post-Workout Nutrition.
        /// </summary>
        internal static string F4DD2D72_6C9A_4E69_9017_95C72291BA8C_Name {
            get {
                return ResourceManager.GetString("F4DD2D72-6C9A-4E69-9017-95C72291BA8C_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string F4DD2D72_6C9A_4E69_9017_95C72291BA8C_Url {
            get {
                return ResourceManager.GetString("F4DD2D72-6C9A-4E69-9017-95C72291BA8C_Url", resourceCulture);
            }
        }
    }
}
