//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BodyArchitect.Module.A6W.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class A6WEntryStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal A6WEntryStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BodyArchitect.Module.A6W.Localization.A6WEntryStrings", typeof(A6WEntryStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional informations about the current training session.
        /// </summary>
        public static string A6W_CommentTXT {
            get {
                return ResourceManager.GetString("A6W_CommentTXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select it if you&apos;ve made all required sets and repetitions..
        /// </summary>
        public static string A6W_CompletedRB {
            get {
                return ResourceManager.GetString("A6W_CompletedRB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every position in this list represents one day in A6W training plan. You can see how many sets and reps every day contains. If the list position (a day) has an icon that this means that this day has been completed..
        /// </summary>
        public static string A6W_LV {
            get {
                return ResourceManager.GetString("A6W_LV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select it if you&apos;ve finished the current day but you didn&apos;t do all required sets or repetitions. Additionally you can type repetitions number below..
        /// </summary>
        public static string A6W_PartialCompletedRB {
            get {
                return ResourceManager.GetString("A6W_PartialCompletedRB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you did less than required you can type how many repetitions you did..
        /// </summary>
        public static string A6W_PartialCompleteSet {
            get {
                return ResourceManager.GetString("A6W_PartialCompleteSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A6W.
        /// </summary>
        public static string A6WCalendarDayContentName {
            get {
                return ResourceManager.GetString("A6WCalendarDayContentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day {0}.
        /// </summary>
        public static string CalendarDayText {
            get {
                return ResourceManager.GetString("CalendarDayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A6W.
        /// </summary>
        public static string EntryTypeName {
            get {
                return ResourceManager.GetString("EntryTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to select result for this day (Completed or Partial completed)..
        /// </summary>
        public static string ErrorA6WDayResultMissing {
            get {
                return ResourceManager.GetString("ErrorA6WDayResultMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A6W training is already started. You need to finish is first..
        /// </summary>
        public static string ErrorA6WTrainingAlreadyStarted {
            get {
                return ResourceManager.GetString("ErrorA6WTrainingAlreadyStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have entered to many repetitions for set {0}. To complete day {1} you need to do {2} repetitions..
        /// </summary>
        public static string ErrorSetTooManyRepetitions {
            get {
                return ResourceManager.GetString("ErrorSetTooManyRepetitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot finish this operation because this would cause break training integrity..
        /// </summary>
        public static string ErrorTrainingIntegrity {
            get {
                return ResourceManager.GetString("ErrorTrainingIntegrity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are starting new training of A6W..
        /// </summary>
        public static string StartNewTrainingText {
            get {
                return ResourceManager.GetString("StartNewTrainingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have completed A6W training. Congratulations.
        /// </summary>
        public static string TrainingCompletedText {
            get {
                return ResourceManager.GetString("TrainingCompletedText", resourceCulture);
            }
        }
    }
}
