//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BodyArchitect.DataAccess.Converter.V4_V5 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BodyArchitect.DataAccess.Converter.V4_V5.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome again!
        ///
        ///We are happy to introduce you a brand new version of BodyArchitect. We&apos;ve added lots of new features and improvements, making the program more effectively in helping you with your training.
        ///
        ///It is impossible to enumerate all the new features you&apos;ll find in the program. We hope you will start discovering things we have prepared for you. One of the biggest changes we want to mention is the introduction of three types of accounts:
        ///-Basic - free, functionally almost the same as the previous [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Message_AdvancedProfile {
            get {
                return ResourceManager.GetString("Message_AdvancedProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome again!
        ///
        ///We are happy to introduce you a brand new version of BodyArchitect. We&apos;ve added lots of new features and improvements, making the program more effectively in helping you with your training.
        ///
        ///It is impossible to enumerate all the new features you&apos;ll find in the program. We hope you will start discovering things we have prepared for you. One of the biggest changes we want to mention is the introduction of three types of accounts:
        ///-Basic - free, functionally almost the same as the previous [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Message_FullWP7Profile {
            get {
                return ResourceManager.GetString("Message_FullWP7Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome again!
        ///
        ///We are happy to introduce you a brand new version of BodyArchitect. We&apos;ve added lots of new features and improvements, making the program more effectively in helping you with your training.
        ///
        ///It is impossible to enumerate all the new features you&apos;ll find in the program. We hope you will start discovering things we have prepared for you. One of the biggest changes we want to mention is the introduction of three types of accounts:
        ///-Basic - free, functionally almost the same as the previous [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Message_NormalProfile {
            get {
                return ResourceManager.GetString("Message_NormalProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version of BodyArchitect!.
        /// </summary>
        internal static string Message_Topic {
            get {
                return ResourceManager.GetString("Message_Topic", resourceCulture);
            }
        }
    }
}
