//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BodyArchitect.Client.Module.GPSTracker.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GPSStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GPSStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BodyArchitect.Client.Module.GPSTracker.Resources.GPSStrings", typeof(GPSStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cardio tracker.
        /// </summary>
        internal static string EntryTypeName {
            get {
                return ResourceManager.GetString("EntryTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Great way to track your cardio activities (running, cycling etc). Use your mobile GPS to gather detailed info about your training..
        /// </summary>
        internal static string EntryTypeShortDescription {
            get {
                return ResourceManager.GetString("EntryTypeShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance: {0:0.#} {1}
        ///.
        /// </summary>
        internal static string GPSTrackerCalendarDayContent_Distance {
            get {
                return ResourceManager.GetString("GPSTrackerCalendarDayContent_Distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duratrion: {0}.
        /// </summary>
        internal static string GPSTrackerCalendarDayContent_Duration {
            get {
                return ResourceManager.GetString("GPSTrackerCalendarDayContent_Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance.
        /// </summary>
        internal static string GpsTrackerChart_XAxis_Distance {
            get {
                return ResourceManager.GetString("GpsTrackerChart_XAxis_Distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        internal static string GpsTrackerChart_XAxis_Time {
            get {
                return ResourceManager.GetString("GpsTrackerChart_XAxis_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Altitude.
        /// </summary>
        internal static string GpsTrackerChart_YAxis_Altitude {
            get {
                return ResourceManager.GetString("GpsTrackerChart_YAxis_Altitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed.
        /// </summary>
        internal static string GpsTrackerChart_YAxis_Speed {
            get {
                return ResourceManager.GetString("GpsTrackerChart_YAxis_Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot retrieve the current weather..
        /// </summary>
        internal static string GPSTrackerViewModel_ErrRetrieveWeather {
            get {
                return ResourceManager.GetString("GPSTrackerViewModel_ErrRetrieveWeather", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured. Please try later...
        /// </summary>
        internal static string GPSTrackerViewModel_ErrRetrievingGpsCoordinates {
            get {
                return ResourceManager.GetString("GPSTrackerViewModel_ErrRetrievingGpsCoordinates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving weather data....
        /// </summary>
        internal static string GPSTrackerViewModel_RetrievingCurrentWeather {
            get {
                return ResourceManager.GetString("GPSTrackerViewModel_RetrievingCurrentWeather", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving gps coordinates....
        /// </summary>
        internal static string GPSTrackerViewModel_RetrievingGpsCoordinates {
            get {
                return ResourceManager.GetString("GPSTrackerViewModel_RetrievingGpsCoordinates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Not available).
        /// </summary>
        internal static string GPSTrackerViewModel_WeatherNotAvailable {
            get {
                return ResourceManager.GetString("GPSTrackerViewModel_WeatherNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get current.
        /// </summary>
        internal static string usrGPSTrackerEntry_Button_RetrieveWeather {
            get {
                return ResourceManager.GetString("usrGPSTrackerEntry_Button_RetrieveWeather", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select an activity first..
        /// </summary>
        internal static string usrGPSTrackerEntry_ErrActivityNull {
            get {
                return ResourceManager.GetString("usrGPSTrackerEntry_ErrActivityNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analysis.
        /// </summary>
        internal static string usrGPSTrackerEntry_Header_Chart {
            get {
                return ResourceManager.GetString("usrGPSTrackerEntry_Header_Chart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string usrGPSTrackerEntry_Header_Details {
            get {
                return ResourceManager.GetString("usrGPSTrackerEntry_Header_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map.
        /// </summary>
        internal static string usrGPSTrackerEntry_Header_Map {
            get {
                return ResourceManager.GetString("usrGPSTrackerEntry_Header_Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weather.
        /// </summary>
        internal static string usrGPSTrackerEntry_Header_Weather {
            get {
                return ResourceManager.GetString("usrGPSTrackerEntry_Header_Weather", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workout.
        /// </summary>
        internal static string usrGPSTrackerEntry_Header_Workout {
            get {
                return ResourceManager.GetString("usrGPSTrackerEntry_Header_Workout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weather is recorded in Premium or Instructor account only.
        /// </summary>
        internal static string usrGPSTrackerEntry_Help_Weather {
            get {
                return ResourceManager.GetString("usrGPSTrackerEntry_Help_Weather", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workout doesn&apos;t have gps coordinates. By using mobile application you can gather gps data which are needed to perform detailed analysys (in Premium or Instructor account only)..
        /// </summary>
        internal static string usrGPSTrackerEntry_InfoEntryWithoutGpsData {
            get {
                return ResourceManager.GetString("usrGPSTrackerEntry_InfoEntryWithoutGpsData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average pace.
        /// </summary>
        internal static string usrGPSTrackerEntry_Label_AvgPace {
            get {
                return ResourceManager.GetString("usrGPSTrackerEntry_Label_AvgPace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average speed.
        /// </summary>
        internal static string usrGPSTrackerEntry_Label_AvgSpeed {
            get {
                return ResourceManager.GetString("usrGPSTrackerEntry_Label_AvgSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calories.
        /// </summary>
        internal static string usrGPSTrackerEntry_Label_Calories {
            get {
                return ResourceManager.GetString("usrGPSTrackerEntry_Label_Calories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Altitude.
        /// </summary>
        internal static string usrGPSTrackerEntry_Label_Chart_Altitude {
            get {
                return ResourceManager.GetString("usrGPSTrackerEntry_Label_Chart_Altitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance.
        /// </summary>
        internal static string usrGPSTrackerEntry_Label_Chart_Distance {
            get {
                return ResourceManager.GetString("usrGPSTrackerEntry_Label_Chart_Distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pace.
        /// </summary>
        internal static string usrGPSTrackerEntry_Label_Chart_Pace {
            get {
                return ResourceManager.GetString("usrGPSTrackerEntry_Label_Chart_Pace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed.
        /// </summary>
        internal static string usrGPSTrackerEntry_Label_Chart_Speed {
            get {
                return ResourceManager.GetString("usrGPSTrackerEntry_Label_Chart_Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        internal static string usrGPSTrackerEntry_Label_Chart_Time {
            get {
                return ResourceManager.GetString("usrGPSTrackerEntry_Label_Chart_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D_istance.
        /// </summary>
        internal static string usrGPSTrackerEntry_Label_Distance {
            get {
                return ResourceManager.GetString("usrGPSTrackerEntry_Label_Distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Duration.
        /// </summary>
        internal static string usrGPSTrackerEntry_Label_Duration {
            get {
                return ResourceManager.GetString("usrGPSTrackerEntry_Label_Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Activity.
        /// </summary>
        internal static string usrGPSTrackerEntry_Label_Exercise {
            get {
                return ResourceManager.GetString("usrGPSTrackerEntry_Label_Exercise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ma_x altitude.
        /// </summary>
        internal static string usrGPSTrackerEntry_Label_MaxAltitude {
            get {
                return ResourceManager.GetString("usrGPSTrackerEntry_Label_MaxAltitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max speed.
        /// </summary>
        internal static string usrGPSTrackerEntry_Label_MaxSpeed {
            get {
                return ResourceManager.GetString("usrGPSTrackerEntry_Label_MaxSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Min altitude.
        /// </summary>
        internal static string usrGPSTrackerEntry_Label_MinAltitude {
            get {
                return ResourceManager.GetString("usrGPSTrackerEntry_Label_MinAltitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total ascent.
        /// </summary>
        internal static string usrGPSTrackerEntry_Label_TotalAscent {
            get {
                return ResourceManager.GetString("usrGPSTrackerEntry_Label_TotalAscent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total descent.
        /// </summary>
        internal static string usrGPSTrackerEntry_Label_TotalDescent {
            get {
                return ResourceManager.GetString("usrGPSTrackerEntry_Label_TotalDescent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to by distance.
        /// </summary>
        internal static string usrGPSTrackerEntry_Radio_Chart_ByDistance {
            get {
                return ResourceManager.GetString("usrGPSTrackerEntry_Radio_Chart_ByDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to by time.
        /// </summary>
        internal static string usrGPSTrackerEntry_Radio_Chart_ByTime {
            get {
                return ResourceManager.GetString("usrGPSTrackerEntry_Radio_Chart_ByTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cardio tracker.
        /// </summary>
        internal static string usrGPSTrackerEntry_RibbonContextPage {
            get {
                return ResourceManager.GetString("usrGPSTrackerEntry_RibbonContextPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map.
        /// </summary>
        internal static string usrGPSTrackerEntry_RibbonGroup_Map {
            get {
                return ResourceManager.GetString("usrGPSTrackerEntry_RibbonGroup_Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Road.
        /// </summary>
        internal static string usrGPSTrackerEntry_RibbonItem_RoadMap {
            get {
                return ResourceManager.GetString("usrGPSTrackerEntry_RibbonItem_RoadMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satelite.
        /// </summary>
        internal static string usrGPSTrackerEntry_RibbonItem_SateliteMap {
            get {
                return ResourceManager.GetString("usrGPSTrackerEntry_RibbonItem_SateliteMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        internal static string usrGPSTrackerEntryDetails_Header_Comments {
            get {
                return ResourceManager.GetString("usrGPSTrackerEntryDetails_Header_Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remind me.
        /// </summary>
        internal static string usrGPSTrackerEntryDetails_Header_Reminder {
            get {
                return ResourceManager.GetString("usrGPSTrackerEntryDetails_Header_Reminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter some comment here.
        /// </summary>
        internal static string usrGPSTrackerEntryDetails_Watermark_Comment {
            get {
                return ResourceManager.GetString("usrGPSTrackerEntryDetails_Watermark_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance:.
        /// </summary>
        internal static string usrLapPushpinInfo_Label_Distance {
            get {
                return ResourceManager.GetString("usrLapPushpinInfo_Label_Distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lap time:.
        /// </summary>
        internal static string usrLapPushpinInfo_Label_LapTime {
            get {
                return ResourceManager.GetString("usrLapPushpinInfo_Label_LapTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total time:.
        /// </summary>
        internal static string usrLapPushpinInfo_Label_TotalTime {
            get {
                return ResourceManager.GetString("usrLapPushpinInfo_Label_TotalTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance ({0}).
        /// </summary>
        internal static string usrLapsDetails_Header_Distance {
            get {
                return ResourceManager.GetString("usrLapsDetails_Header_Distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lap time.
        /// </summary>
        internal static string usrLapsDetails_Header_LapTime {
            get {
                return ResourceManager.GetString("usrLapsDetails_Header_LapTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pace ({0}).
        /// </summary>
        internal static string usrLapsDetails_Header_Pace {
            get {
                return ResourceManager.GetString("usrLapsDetails_Header_Pace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed ({0}).
        /// </summary>
        internal static string usrLapsDetails_Header_Speed {
            get {
                return ResourceManager.GetString("usrLapsDetails_Header_Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total time.
        /// </summary>
        internal static string usrLapsDetails_Header_TotalTime {
            get {
                return ResourceManager.GetString("usrLapsDetails_Header_TotalTime", resourceCulture);
            }
        }
    }
}
