//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.237
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BodyArchitect.Controls.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ApplicationStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApplicationStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BodyArchitect.Controls.Localization.ApplicationStrings", typeof(ApplicationStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string AddButton {
            get {
                return ResourceManager.GetString("AddButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of followers.
        /// </summary>
        public static string ApplicationStrings_UserStatistics_FollowersCountToolTip {
            get {
                return ResourceManager.GetString("ApplicationStrings.UserStatistics_FollowersCountToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Open....
        /// </summary>
        public static string BTNEditExercise {
            get {
                return ResourceManager.GetString("BTNEditExercise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Add....
        /// </summary>
        public static string BTNNewExercise {
            get {
                return ResourceManager.GetString("BTNNewExercise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workouts-{0}.
        /// </summary>
        public static string CalendarViewForUser_TabText {
            get {
                return ResourceManager.GetString("CalendarViewForUser_TabText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelling....
        /// </summary>
        public static string CancelingOperation {
            get {
                return ResourceManager.GetString("CancelingOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string CloseButton {
            get {
                return ResourceManager.GetString("CloseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string CMBExerciseName {
            get {
                return ResourceManager.GetString("CMBExerciseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortcut.
        /// </summary>
        public static string CMBExerciseShortcut {
            get {
                return ResourceManager.GetString("CMBExerciseShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string CMBExerciseType {
            get {
                return ResourceManager.GetString("CMBExerciseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string ColumnExerciseName {
            get {
                return ResourceManager.GetString("ColumnExerciseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortcut.
        /// </summary>
        public static string ColumnExerciseShortcut {
            get {
                return ResourceManager.GetString("ColumnExerciseShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed: {0}%.
        /// </summary>
        public static string CompletePercentageResult {
            get {
                return ResourceManager.GetString("CompletePercentageResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  ago.
        /// </summary>
        public static string DateTimeExtension_AgoPostfix {
            get {
                return ResourceManager.GetString("DateTimeExtension_AgoPostfix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  from now.
        /// </summary>
        public static string DateTimeExtension_FromNowSuffix {
            get {
                return ResourceManager.GetString("DateTimeExtension_FromNowSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Less than a minute.
        /// </summary>
        public static string DateTimeExtension_LessThanMinute {
            get {
                return ResourceManager.GetString("DateTimeExtension_LessThanMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A day.
        /// </summary>
        public static string DateTimeExtension_OneDay {
            get {
                return ResourceManager.GetString("DateTimeExtension_OneDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About an hour.
        /// </summary>
        public static string DateTimeExtension_OneHour {
            get {
                return ResourceManager.GetString("DateTimeExtension_OneHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About a minute.
        /// </summary>
        public static string DateTimeExtension_OneMinute {
            get {
                return ResourceManager.GetString("DateTimeExtension_OneMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About a month.
        /// </summary>
        public static string DateTimeExtension_OneMonth {
            get {
                return ResourceManager.GetString("DateTimeExtension_OneMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About a month ago.
        /// </summary>
        public static string DateTimeExtension_OneMonthAgo {
            get {
                return ResourceManager.GetString("DateTimeExtension_OneMonthAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About a year.
        /// </summary>
        public static string DateTimeExtension_OneYear {
            get {
                return ResourceManager.GetString("DateTimeExtension_OneYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About a year ago.
        /// </summary>
        public static string DateTimeExtension_OneYearAgo {
            get {
                return ResourceManager.GetString("DateTimeExtension_OneYearAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        public static string DateTimeExtension_Today {
            get {
                return ResourceManager.GetString("DateTimeExtension_Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} days.
        /// </summary>
        public static string DateTimeExtension_XDays {
            get {
                return ResourceManager.GetString("DateTimeExtension_XDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} days ago.
        /// </summary>
        public static string DateTimeExtension_XDaysAgo {
            get {
                return ResourceManager.GetString("DateTimeExtension_XDaysAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About {0} hours.
        /// </summary>
        public static string DateTimeExtension_XHours {
            get {
                return ResourceManager.GetString("DateTimeExtension_XHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} minutes.
        /// </summary>
        public static string DateTimeExtension_XMinutes {
            get {
                return ResourceManager.GetString("DateTimeExtension_XMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} months.
        /// </summary>
        public static string DateTimeExtension_XMonths {
            get {
                return ResourceManager.GetString("DateTimeExtension_XMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} months ago.
        /// </summary>
        public static string DateTimeExtension_XMonthsAgo {
            get {
                return ResourceManager.GetString("DateTimeExtension_XMonthsAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} years.
        /// </summary>
        public static string DateTimeExtension_XYears {
            get {
                return ResourceManager.GetString("DateTimeExtension_XYears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} years ago.
        /// </summary>
        public static string DateTimeExtension_XYearsAgo {
            get {
                return ResourceManager.GetString("DateTimeExtension_XYearsAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yesterday.
        /// </summary>
        public static string DateTimeExtension_Yesterday {
            get {
                return ResourceManager.GetString("DateTimeExtension_Yesterday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Deleted).
        /// </summary>
        public static string DeletedObject {
            get {
                return ResourceManager.GetString("DeletedObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Select an exercise].
        /// </summary>
        public static string EmptyExerciseCellText {
            get {
                return ResourceManager.GetString("EmptyExerciseCellText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create the profile..
        /// </summary>
        public static string ErrCannotCreateProfile {
            get {
                return ResourceManager.GetString("ErrCannotCreateProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete the message. More information can be found in the log file. Error code = {0}.
        /// </summary>
        public static string ErrCannotDeleteMessage {
            get {
                return ResourceManager.GetString("ErrCannotDeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This message does not exist or has been removed..
        /// </summary>
        public static string ErrMessageDoesntExist {
            get {
                return ResourceManager.GetString("ErrMessageDoesntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to login. Please check your log file. Error code: {0}.
        /// </summary>
        public static string ErrorAuthentication {
            get {
                return ResourceManager.GetString("ErrorAuthentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username or password..
        /// </summary>
        public static string ErrorAuthenticationWrongCredentials {
            get {
                return ResourceManager.GetString("ErrorAuthenticationWrongCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to add user to your Favorites list..
        /// </summary>
        public static string ErrorCannotAddUserToFavorites {
            get {
                return ResourceManager.GetString("ErrorCannotAddUserToFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It cannot be empty.
        /// </summary>
        public static string ErrorCannotBeEmpty {
            get {
                return ResourceManager.GetString("ErrorCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to copy this day because it contains only permanent entries..
        /// </summary>
        public static string ErrorCannotCopyTrainingDayFixedEntries {
            get {
                return ResourceManager.GetString("ErrorCannotCopyTrainingDayFixedEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can not delete the specified day because some entries are part of the training..
        /// </summary>
        public static string ErrorCannotDeleteTrainingDayPartOfTraining {
            get {
                return ResourceManager.GetString("ErrorCannotDeleteTrainingDayPartOfTraining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to generate a report. Please check your log file. Error code: {0}..
        /// </summary>
        public static string ErrorCannotGenerateReport {
            get {
                return ResourceManager.GetString("ErrorCannotGenerateReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to log on to the deleted profile..
        /// </summary>
        public static string ErrorCannotLoginToDeletedProfile {
            get {
                return ResourceManager.GetString("ErrorCannotLoginToDeletedProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot move selected training day because it contains fixed entries..
        /// </summary>
        public static string ErrorCannotMoveTrainingDayFixedEntries {
            get {
                return ResourceManager.GetString("ErrorCannotMoveTrainingDayFixedEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected day already has an entry. You must first delete the existing entry..
        /// </summary>
        public static string ErrorCannotPaste {
            get {
                return ResourceManager.GetString("ErrorCannotPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete user from the list of favorites..
        /// </summary>
        public static string ErrorCannotRemoveUserFromFavorites {
            get {
                return ResourceManager.GetString("ErrorCannotRemoveUserFromFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to open log file..
        /// </summary>
        public static string ErrorCannotShowLogFile {
            get {
                return ResourceManager.GetString("ErrorCannotShowLogFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured while checking for updates. Please check your log file. Error code: {0}.
        /// </summary>
        public static string ErrorCheckUpdates {
            get {
                return ResourceManager.GetString("ErrorCheckUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem with the connection to the server. Please try again later..
        /// </summary>
        public static string ErrorConnectionProblem {
            get {
                return ResourceManager.GetString("ErrorConnectionProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured while creating the profile. Please check your log file. Error code: {0}.
        /// </summary>
        public static string ErrorCreateProfile {
            get {
                return ResourceManager.GetString("ErrorCreateProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile with the specified name already exists. Please enter a different name..
        /// </summary>
        public static string ErrorCreateProfileUnique {
            get {
                return ResourceManager.GetString("ErrorCreateProfileUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your profile has been deleted. You will be logout.
        /// </summary>
        public static string ErrorCurrentProfileDeleted {
            get {
                return ResourceManager.GetString("ErrorCurrentProfileDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete the file. Please check your log file. Error code: {0}.
        /// </summary>
        public static string ErrorDeleteLogFile {
            get {
                return ResourceManager.GetString("ErrorDeleteLogFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete the profile. Please check your log file. Error code: {0}.
        /// </summary>
        public static string ErrorDeleteProfile {
            get {
                return ResourceManager.GetString("ErrorDeleteProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred during checking update of application.
        /// </summary>
        public static string ErrorDuringCheckingUpdates {
            get {
                return ResourceManager.GetString("ErrorDuringCheckingUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured while updating the application. Please check your log file. Error code: {0}.
        /// </summary>
        public static string ErrorDuringUpdates {
            get {
                return ResourceManager.GetString("ErrorDuringUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred during the update..
        /// </summary>
        public static string ErrorDuringUpdatingApplication {
            get {
                return ResourceManager.GetString("ErrorDuringUpdatingApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot add this type of entry more than once..
        /// </summary>
        public static string ErrorEntryObjectTypeAlreadyExists {
            get {
                return ResourceManager.GetString("ErrorEntryObjectTypeAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred during retrieving the data. Application will be closed. Please see the log file. Exception Id: {0}.
        /// </summary>
        public static string ErrorFillCalendarView {
            get {
                return ResourceManager.GetString("ErrorFillCalendarView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured while viewing. Please check your log file. Error code: {0}.
        /// </summary>
        public static string ErrorFillTrainingDay {
            get {
                return ResourceManager.GetString("ErrorFillTrainingDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exercise with identical ID alreday exists in the database. The exercise must have already been imported into the database..
        /// </summary>
        public static string ErrorImportExercisesUnique {
            get {
                return ResourceManager.GetString("ErrorImportExercisesUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current database is intended for a different BodyArchitect version. The program will be closed..
        /// </summary>
        public static string ErrorInvalidDatabaseVersion {
            get {
                return ResourceManager.GetString("ErrorInvalidDatabaseVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The invitation does not exist or has been removed..
        /// </summary>
        public static string ErrorInvitationDoesntExist {
            get {
                return ResourceManager.GetString("ErrorInvitationDoesntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while downloading the profile. Please check your log file. Error code: {0}.
        /// </summary>
        public static string ErrorLoadProfile {
            get {
                return ResourceManager.GetString("ErrorLoadProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BodyArchitect is temporary unavailable. This is due to software updates. Please try again later..
        /// </summary>
        public static string ErrorMaintenanceMode {
            get {
                return ResourceManager.GetString("ErrorMaintenanceMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to move the entry. Please see the log file. Error code: {0}.
        /// </summary>
        public static string ErrorMoveTrainingDay {
            get {
                return ResourceManager.GetString("ErrorMoveTrainingDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your email. We have sent an email with your account activation link. Please click on it to complete the registration of your account..
        /// </summary>
        public static string ErrorMustActivateProfile {
            get {
                return ResourceManager.GetString("ErrorMustActivateProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It must be unique and cannot be empty.
        /// </summary>
        public static string ErrorMustBeUnique {
            get {
                return ResourceManager.GetString("ErrorMustBeUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The modified data has been changed on the server. Please refresh the view and try again..
        /// </summary>
        public static string ErrorOldDataModification {
            get {
                return ResourceManager.GetString("ErrorOldDataModification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected day has been currently changed on the server and contains diffrent data. Please refresh the view..
        /// </summary>
        public static string ErrorOldTrainingDay {
            get {
                return ResourceManager.GetString("ErrorOldTrainingDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have an older version of the program. Please download the latest version and try again..
        /// </summary>
        public static string ErrorOldVersionOfBodyArchitect {
            get {
                return ResourceManager.GetString("ErrorOldVersionOfBodyArchitect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot start the webbrowser..
        /// </summary>
        public static string ErrorOpenWebBrowser {
            get {
                return ResourceManager.GetString("ErrorOpenWebBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to open the page. Please run a web browser and enter the address manually..
        /// </summary>
        public static string ErrorOpenWebSite {
            get {
                return ResourceManager.GetString("ErrorOpenWebSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected profile is deleted, hence you cannot perform the current operation..
        /// </summary>
        public static string ErrorProfileDeleted {
            get {
                return ResourceManager.GetString("ErrorProfileDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The profile is already activated..
        /// </summary>
        public static string ErrorProfileIsActivated {
            get {
                return ResourceManager.GetString("ErrorProfileIsActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must activate your account first.
        /// </summary>
        public static string ErrorProfileNotActivated {
            get {
                return ResourceManager.GetString("ErrorProfileNotActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during exercise removal. Please check your log file. Error code: {0}.
        /// </summary>
        public static string ErrorRemoveExercise {
            get {
                return ResourceManager.GetString("ErrorRemoveExercise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while deleting. Please check your log file. Error code: {0}}.
        /// </summary>
        public static string ErrorRemoveTrainingDay {
            get {
                return ResourceManager.GetString("ErrorRemoveTrainingDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve the news..
        /// </summary>
        public static string ErrorRetrievingRssFeed {
            get {
                return ResourceManager.GetString("ErrorRetrievingRssFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while saving. Please check your log file. Error code: {0}}.
        /// </summary>
        public static string ErrorSaveExercise {
            get {
                return ResourceManager.GetString("ErrorSaveExercise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exercise shortcut must be unique. Choose a different shortcut..
        /// </summary>
        public static string ErrorSaveExerciseUnique {
            get {
                return ResourceManager.GetString("ErrorSaveExerciseUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save the file. Please check your log file. Error code: {0}.
        /// </summary>
        public static string ErrorSaveLogFile {
            get {
                return ResourceManager.GetString("ErrorSaveLogFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while saving the profile. Please check your log file. Error code: {0}}.
        /// </summary>
        public static string ErrorSaveProfile {
            get {
                return ResourceManager.GetString("ErrorSaveProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while saving. Please check your log file. Error code: {0}}.
        /// </summary>
        public static string ErrorSaveTrainingDay {
            get {
                return ResourceManager.GetString("ErrorSaveTrainingDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to display a smaller number of series than the current number of series in the exercises..
        /// </summary>
        public static string ErrorSerieColumnCount {
            get {
                return ResourceManager.GetString("ErrorSerieColumnCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot insert A6W entry in the middle of the started training..
        /// </summary>
        public static string ErrorTrainingIntegrity {
            get {
                return ResourceManager.GetString("ErrorTrainingIntegrity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application initialisation failed. Please check your log file. Error code: {0}.
        /// </summary>
        public static string ErrorUnableConfigureNHibernate {
            get {
                return ResourceManager.GetString("ErrorUnableConfigureNHibernate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to import the exercises. Please check your log file. Error code: {0}..
        /// </summary>
        public static string ErrorUnableToImportExercises {
            get {
                return ResourceManager.GetString("ErrorUnableToImportExercises", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred. Please check your log file. Error code: {0}.
        /// </summary>
        public static string ErrorUnhandledException {
            get {
                return ResourceManager.GetString("ErrorUnhandledException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem with sending email. Please try again later..
        /// </summary>
        public static string ErrProblemWithSendingEmail {
            get {
                return ResourceManager.GetString("ErrProblemWithSendingEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activation email has been sent. Please check your email..
        /// </summary>
        public static string ForgotPasswordWindow_ActivatedEmailSent {
            get {
                return ResourceManager.GetString("ForgotPasswordWindow_ActivatedEmailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been changed. Please check your email..
        /// </summary>
        public static string ForgotPasswordWindow_PasswordChangedInfo {
            get {
                return ResourceManager.GetString("ForgotPasswordWindow_PasswordChangedInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given username or e-mail address was not found in our database..
        /// </summary>
        public static string ForgotPasswordWindow_ProfileNotFoundError {
            get {
                return ResourceManager.GetString("ForgotPasswordWindow_ProfileNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your username or e-mail address (the same you entered when creating your account.) Activation email will be sent to your inbox..
        /// </summary>
        public static string ForgotPasswordWindow_SendActivationEmailDescription {
            get {
                return ResourceManager.GetString("ForgotPasswordWindow_SendActivationEmailDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send e-mail with account activation.
        /// </summary>
        public static string ForgotPasswordWindow_SendActivationEmailTitle {
            get {
                return ResourceManager.GetString("ForgotPasswordWindow_SendActivationEmailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New language will be available after restarting the application..
        /// </summary>
        public static string InfoChangeLanguageRestart {
            get {
                return ResourceManager.GetString("InfoChangeLanguageRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialising....
        /// </summary>
        public static string InfoInicializingApplication {
            get {
                return ResourceManager.GetString("InfoInicializingApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the last entry in the database..
        /// </summary>
        public static string InfoNextEntryLimit {
            get {
                return ResourceManager.GetString("InfoNextEntryLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This profile does not contain any entries..
        /// </summary>
        public static string InfoNoTrainingDayEntires {
            get {
                return ResourceManager.GetString("InfoNoTrainingDayEntires", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have installed the latest version of the program..
        /// </summary>
        public static string InfoNoUpdatesAvailable {
            get {
                return ResourceManager.GetString("InfoNoUpdatesAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing the data ....
        /// </summary>
        public static string InfoPreparingData {
            get {
                return ResourceManager.GetString("InfoPreparingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the first entry in the database..
        /// </summary>
        public static string InfoPreviousEntryLimit {
            get {
                return ResourceManager.GetString("InfoPreviousEntryLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes will take effect after restarting the program..
        /// </summary>
        public static string InfoRestartAfterUpdates {
            get {
                return ResourceManager.GetString("InfoRestartAfterUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A newer version of the program is available and it is essential for proper operation. After clicking Ok, your application will be updated..
        /// </summary>
        public static string InfoUpdateRequired {
            get {
                return ResourceManager.GetString("InfoUpdateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cm.
        /// </summary>
        public static string LengthType_Cm {
            get {
                return ResourceManager.GetString("LengthType_Cm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to inch.
        /// </summary>
        public static string LengthType_Inch {
            get {
                return ResourceManager.GetString("LengthType_Inch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide connection settings....
        /// </summary>
        public static string LoginWindow_HideConnectionSettings {
            get {
                return ResourceManager.GetString("LoginWindow_HideConnectionSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show connection settings....
        /// </summary>
        public static string LoginWindow_ShowConnectionSettings {
            get {
                return ResourceManager.GetString("LoginWindow_ShowConnectionSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - {1}.
        /// </summary>
        public static string MainWindowTitle {
            get {
                return ResourceManager.GetString("MainWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipient.
        /// </summary>
        public static string Message_Receiver {
            get {
                return ResourceManager.GetString("Message_Receiver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sender.
        /// </summary>
        public static string Message_Sender {
            get {
                return ResourceManager.GetString("Message_Sender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;New....
        /// </summary>
        public static string MNUNewTrainingDay {
            get {
                return ResourceManager.GetString("MNUNewTrainingDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Open....
        /// </summary>
        public static string MNUOpenTrainingDay {
            get {
                return ResourceManager.GetString("MNUOpenTrainingDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not logged in.
        /// </summary>
        public static string NotLoggedText {
            get {
                return ResourceManager.GetString("NotLoggedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar.
        /// </summary>
        public static string OptionsCalendarTitle {
            get {
                return ResourceManager.GetString("OptionsCalendarTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Misc.
        /// </summary>
        public static string OptionsReportingTitle {
            get {
                return ResourceManager.GetString("OptionsReportingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some changes require you to restart the application..
        /// </summary>
        public static string OptionsRestartRequiredMsg {
            get {
                return ResourceManager.GetString("OptionsRestartRequiredMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded {0} of {1}.
        /// </summary>
        public static string PartialLoadedStatus {
            get {
                return ResourceManager.GetString("PartialLoadedStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error image.
        /// </summary>
        public static string PhotoDoesntExist {
            get {
                return ResourceManager.GetString("PhotoDoesntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string PluginsGrid_DefaultEntryColumn {
            get {
                return ResourceManager.GetString("PluginsGrid_DefaultEntryColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon.
        /// </summary>
        public static string PluginsGrid_IconColumn {
            get {
                return ResourceManager.GetString("PluginsGrid_IconColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module.
        /// </summary>
        public static string PluginsGrid_PluginColumn {
            get {
                return ResourceManager.GetString("PluginsGrid_PluginColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing....
        /// </summary>
        public static string ProgressIndicator_Processing {
            get {
                return ResourceManager.GetString("ProgressIndicator_Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish.
        /// </summary>
        public static string PublishButton {
            get {
                return ResourceManager.GetString("PublishButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to clear this log?.
        /// </summary>
        public static string QAskClearLog {
            get {
                return ResourceManager.GetString("QAskClearLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this entry: {0}?.
        /// </summary>
        public static string QAskForDeletingEntryObject {
            get {
                return ResourceManager.GetString("QAskForDeletingEntryObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to make the selected exercise public?.
        /// </summary>
        public static string QAskForPublicationExercise {
            get {
                return ResourceManager.GetString("QAskForPublicationExercise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to cancel editing?.
        /// </summary>
        public static string QCloseTrainingDay {
            get {
                return ResourceManager.GetString("QCloseTrainingDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete this message?.
        /// </summary>
        public static string QDeleteMessage {
            get {
                return ResourceManager.GetString("QDeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete the current profile? After this operation, the profile will not be able to be logged in, and all data will be lost..
        /// </summary>
        public static string QDeleteProfile {
            get {
                return ResourceManager.GetString("QDeleteProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete a selected messages?.
        /// </summary>
        public static string QDeleteSelectedMessages {
            get {
                return ResourceManager.GetString("QDeleteSelectedMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to move this entry?.
        /// </summary>
        public static string QMoveTrainingDay {
            get {
                return ResourceManager.GetString("QMoveTrainingDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the selected exercise? This will also delete all training entries containing the removed exercise!.
        /// </summary>
        public static string QRemoveExercise {
            get {
                return ResourceManager.GetString("QRemoveExercise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the entry from {0}?.
        /// </summary>
        public static string QRemoveTrainingDay {
            get {
                return ResourceManager.GetString("QRemoveTrainingDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to restore the default settings?.
        /// </summary>
        public static string QResetAllOptions {
            get {
                return ResourceManager.GetString("QResetAllOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The report has been generated in the {0}..
        /// </summary>
        public static string Reporting_GeneratingTimeStatus {
            get {
                return ResourceManager.GetString("Reporting_GeneratingTimeStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (None).
        /// </summary>
        public static string ReportingOptions_NoTemplate {
            get {
                return ResourceManager.GetString("ReportingOptions_NoTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Png file (*.png)|*.png|Jpeg (*.jpg)|*.jpg|Bitmap (*.bmp)|*.bmp.
        /// </summary>
        public static string ReportSavingFilter {
            get {
                return ResourceManager.GetString("ReportSavingFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports-{0}.
        /// </summary>
        public static string ReportsForUser_TabText {
            get {
                return ResourceManager.GetString("ReportsForUser_TabText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        public static string RssHeaderNews {
            get {
                return ResourceManager.GetString("RssHeaderNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tips &amp; Tricks.
        /// </summary>
        public static string RssHeaderTips {
            get {
                return ResourceManager.GetString("RssHeaderTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text file (*.txt)|*.txt|Log file (*.log)|*.log|All files (*.*)|*.*.
        /// </summary>
        public static string SaveLogFileFilter {
            get {
                return ResourceManager.GetString("SaveLogFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Choose the report).
        /// </summary>
        public static string SelectReportText {
            get {
                return ResourceManager.GetString("SelectReportText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string SpecificCulture {
            get {
                return ResourceManager.GetString("SpecificCulture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking out for a newer version of the program ....
        /// </summary>
        public static string SplashScreen_CheckingNewVersion {
            get {
                return ResourceManager.GetString("SplashScreen_CheckingNewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading the new version of {2}: {0}/{1}.
        /// </summary>
        public static string SplashScreen_DownloadingNewVersion {
            get {
                return ResourceManager.GetString("SplashScreen_DownloadingNewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new version of {0} has appeared. Preparing for updates ....
        /// </summary>
        public static string SplashScreen_NewVersionFound {
            get {
                return ResourceManager.GetString("SplashScreen_NewVersionFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing the GUI ....
        /// </summary>
        public static string SplasScreen_PreparingGUI {
            get {
                return ResourceManager.GetString("SplasScreen_PreparingGUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar view: {0}.
        /// </summary>
        public static string StatusBarCalendarViewText {
            get {
                return ResourceManager.GetString("StatusBarCalendarViewText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can see the calendar of this user.
        /// </summary>
        public static string UserListView_CalendarAllowedToolTip {
            get {
                return ResourceManager.GetString("UserListView_CalendarAllowedToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can see the measurements of this user.
        /// </summary>
        public static string UserListView_MeasurementsAllowedToolTip {
            get {
                return ResourceManager.GetString("UserListView_MeasurementsAllowedToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorites.
        /// </summary>
        public static string UsersListView_Group_Favorites {
            get {
                return ResourceManager.GetString("UsersListView_Group_Favorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friends.
        /// </summary>
        public static string UsersListView_Group_Friends {
            get {
                return ResourceManager.GetString("UsersListView_Group_Friends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Others.
        /// </summary>
        public static string UsersListView_Group_Others {
            get {
                return ResourceManager.GetString("UsersListView_Group_Others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of given comments: {0}.
        /// </summary>
        public static string UserStatistics_BlogCommentsCountText {
            get {
                return ResourceManager.GetString("UserStatistics_BlogCommentsCountText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of followers: {0}.
        /// </summary>
        public static string UserStatistics_FollowersCountText {
            get {
                return ResourceManager.GetString("UserStatistics_FollowersCountText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of friends: {0}.
        /// </summary>
        public static string UserStatistics_FriendsCountText {
            get {
                return ResourceManager.GetString("UserStatistics_FriendsCountText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last entry: {0}.
        /// </summary>
        public static string UserStatistics_LastEntryDateText {
            get {
                return ResourceManager.GetString("UserStatistics_LastEntryDateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last entry date: {0}.
        /// </summary>
        public static string UserStatistics_LastEntryDateToolTip {
            get {
                return ResourceManager.GetString("UserStatistics_LastEntryDateToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last login: {0}.
        /// </summary>
        public static string UserStatistics_LastLogin {
            get {
                return ResourceManager.GetString("UserStatistics_LastLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of my blogs comments: {0}.
        /// </summary>
        public static string UserStatistics_MyBlogCommentsCount {
            get {
                return ResourceManager.GetString("UserStatistics_MyBlogCommentsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} medal in {1} category..
        /// </summary>
        public static string UserStatistics_StarToolTip {
            get {
                return ResourceManager.GetString("UserStatistics_StarToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strength training entries: {0}.
        /// </summary>
        public static string UserStatistics_StrengthTrainingEntriesCount {
            get {
                return ResourceManager.GetString("UserStatistics_StrengthTrainingEntriesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of entries in the calendar.
        /// </summary>
        public static string UserStatistics_TrainingDaysCount {
            get {
                return ResourceManager.GetString("UserStatistics_TrainingDaysCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entries in calendar: {0}.
        /// </summary>
        public static string UserStatistics_TrainingDaysCountText {
            get {
                return ResourceManager.GetString("UserStatistics_TrainingDaysCountText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of votes: {0}.
        /// </summary>
        public static string UserStatistics_VotesCountText {
            get {
                return ResourceManager.GetString("UserStatistics_VotesCountText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of public workout plans created by this user.
        /// </summary>
        public static string UserStatistics_WorkoutPlansCountToolTip {
            get {
                return ResourceManager.GetString("UserStatistics_WorkoutPlansCountToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workout plans: {0}.
        /// </summary>
        public static string UserStatistics_WorkoutPlansText {
            get {
                return ResourceManager.GetString("UserStatistics_WorkoutPlansText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invitations ({0}).
        /// </summary>
        public static string usrInvitationsView_Caption {
            get {
                return ResourceManager.GetString("usrInvitationsView_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages ({0}).
        /// </summary>
        public static string usrMessagesBoard_Caption {
            get {
                return ResourceManager.GetString("usrMessagesBoard_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message ({0}).
        /// </summary>
        public static string usrMessageView_MessageGroup_Text {
            get {
                return ResourceManager.GetString("usrMessageView_MessageGroup_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RE: {0}.
        /// </summary>
        public static string usrMessageView_ReplyTopic {
            get {
                return ResourceManager.GetString("usrMessageView_ReplyTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tips {0}/{1}: {2}.
        /// </summary>
        public static string usrRssReader_TipTitle {
            get {
                return ResourceManager.GetString("usrRssReader_TipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User information.
        /// </summary>
        public static string usrUserInfo_Caption_UserInformation {
            get {
                return ResourceManager.GetString("usrUserInfo_Caption_UserInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have {0} invitations..
        /// </summary>
        public static string usrUserInfo_InvitationsCount {
            get {
                return ResourceManager.GetString("usrUserInfo_InvitationsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last login: {0}.
        /// </summary>
        public static string usrUserInfo_LastLogin {
            get {
                return ResourceManager.GetString("usrUserInfo_LastLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have {0} messages..
        /// </summary>
        public static string usrUserInfo_MessagesCount {
            get {
                return ResourceManager.GetString("usrUserInfo_MessagesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept invitation.
        /// </summary>
        public static string usrUserInvitationEntry_AcceptInvitation_ToolTip {
            get {
                return ResourceManager.GetString("usrUserInvitationEntry_AcceptInvitation_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel invitation.
        /// </summary>
        public static string usrUserInvitationEntry_CancelInvitation_ToolTip {
            get {
                return ResourceManager.GetString("usrUserInvitationEntry_CancelInvitation_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message from the user:.
        /// </summary>
        public static string usrUserInvitationEntry_MessageText {
            get {
                return ResourceManager.GetString("usrUserInvitationEntry_MessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (User did&apos;t put a message).
        /// </summary>
        public static string usrUserInvitationEntry_NoMessageText {
            get {
                return ResourceManager.GetString("usrUserInvitationEntry_NoMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject invitation.
        /// </summary>
        public static string usrUserInvitationEntry_RejectInvitation_ToolTIp {
            get {
                return ResourceManager.GetString("usrUserInvitationEntry_RejectInvitation_ToolTIp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have been invited to this user&apos;s circle of friends..
        /// </summary>
        public static string usrUserInvitationEntry_YouAreInvitedByUser_Msg {
            get {
                return ResourceManager.GetString("usrUserInvitationEntry_YouAreInvitedByUser_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invite this user to the circle of friends..
        /// </summary>
        public static string usrUserInvitationEntry_YouInvitedThisUser_Msg {
            get {
                return ResourceManager.GetString("usrUserInvitationEntry_YouInvitedThisUser_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measurements.
        /// </summary>
        public static string usrUserSizes_Caption {
            get {
                return ResourceManager.GetString("usrUserSizes_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kg.
        /// </summary>
        public static string WeightType_Kg {
            get {
                return ResourceManager.GetString("WeightType_Kg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lbs.
        /// </summary>
        public static string WeightType_Pound {
            get {
                return ResourceManager.GetString("WeightType_Pound", resourceCulture);
            }
        }
    }
}
