//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BodyArchitect.Controls.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DomainModelStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DomainModelStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BodyArchitect.Controls.Localization.DomainModelStrings", typeof(DomainModelStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Famous.
        /// </summary>
        public static string AchievementCategory_Famous {
            get {
                return ResourceManager.GetString("AchievementCategory_Famous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social.
        /// </summary>
        public static string AchievementCategory_Social {
            get {
                return ResourceManager.GetString("AchievementCategory_Social", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sport.
        /// </summary>
        public static string AchievementCategory_Sport {
            get {
                return ResourceManager.GetString("AchievementCategory_Sport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AchievementRank_Rank1 {
            get {
                return ResourceManager.GetString("AchievementRank_Rank1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beginner.
        /// </summary>
        public static string AchievementRank_Rank2 {
            get {
                return ResourceManager.GetString("AchievementRank_Rank2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resident.
        /// </summary>
        public static string AchievementRank_Rank3 {
            get {
                return ResourceManager.GetString("AchievementRank_Rank3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maniac.
        /// </summary>
        public static string AchievementRank_Rank4 {
            get {
                return ResourceManager.GetString("AchievementRank_Rank4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expert.
        /// </summary>
        public static string AchievementRank_Rank5 {
            get {
                return ResourceManager.GetString("AchievementRank_Rank5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veteran.
        /// </summary>
        public static string AchievementRank_Rank6 {
            get {
                return ResourceManager.GetString("AchievementRank_Rank6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bronze.
        /// </summary>
        public static string AchievementStar_Bronze {
            get {
                return ResourceManager.GetString("AchievementStar_Bronze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gold.
        /// </summary>
        public static string AchievementStar_Gold {
            get {
                return ResourceManager.GetString("AchievementStar_Gold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string AchievementStar_None {
            get {
                return ResourceManager.GetString("AchievementStar_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silver.
        /// </summary>
        public static string AchievementStar_Silver {
            get {
                return ResourceManager.GetString("AchievementStar_Silver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obesity of 3rd degree.
        /// </summary>
        public static string BmiResult_IIIStopienOtylosci {
            get {
                return ResourceManager.GetString("BmiResult_IIIStopienOtylosci", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obesity of 2nd degree.
        /// </summary>
        public static string BmiResult_IIStopienOtylosci {
            get {
                return ResourceManager.GetString("BmiResult_IIStopienOtylosci", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Invalid data).
        /// </summary>
        public static string BmiResult_Incorrect {
            get {
                return ResourceManager.GetString("BmiResult_Incorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obesity of 1st degree.
        /// </summary>
        public static string BmiResult_IStopienOtylosci {
            get {
                return ResourceManager.GetString("BmiResult_IStopienOtylosci", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Underweight.
        /// </summary>
        public static string BmiResult_Niedowaga {
            get {
                return ResourceManager.GetString("BmiResult_Niedowaga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        public static string BmiResult_Normal {
            get {
                return ResourceManager.GetString("BmiResult_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overweight.
        /// </summary>
        public static string BmiResult_PrzedOtyloscia {
            get {
                return ResourceManager.GetString("BmiResult_PrzedOtyloscia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emaciation.
        /// </summary>
        public static string BmiResult_Wychudzenie {
            get {
                return ResourceManager.GetString("BmiResult_Wychudzenie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Severe emaciation.
        /// </summary>
        public static string BmiResult_Wyglodzenie {
            get {
                return ResourceManager.GetString("BmiResult_Wyglodzenie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading application files.
        /// </summary>
        public static string DeploymentProgressState_DownloadingApplicationFiles {
            get {
                return ResourceManager.GetString("DeploymentProgressState_DownloadingApplicationFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving application data.
        /// </summary>
        public static string DeploymentProgressState_DownloadingApplicationInformation {
            get {
                return ResourceManager.GetString("DeploymentProgressState_DownloadingApplicationInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving information about an update.
        /// </summary>
        public static string DeploymentProgressState_DownloadingDeploymentInformation {
            get {
                return ResourceManager.GetString("DeploymentProgressState_DownloadingDeploymentInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grams.
        /// </summary>
        public static string DosageType_Grams {
            get {
                return ResourceManager.GetString("DosageType_Grams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servings.
        /// </summary>
        public static string DosageType_Servings {
            get {
                return ResourceManager.GetString("DosageType_Servings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tablets.
        /// </summary>
        public static string DosageType_Tablets {
            get {
                return ResourceManager.GetString("DosageType_Tablets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Units.
        /// </summary>
        public static string DosageType_Units {
            get {
                return ResourceManager.GetString("DosageType_Units", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Not set).
        /// </summary>
        public static string ExerciseForceType_NotSet {
            get {
                return ResourceManager.GetString("ExerciseForceType_NotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pull.
        /// </summary>
        public static string ExerciseForceType_Pull {
            get {
                return ResourceManager.GetString("ExerciseForceType_Pull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Push.
        /// </summary>
        public static string ExerciseForceType_Push {
            get {
                return ResourceManager.GetString("ExerciseForceType_Push", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Static.
        /// </summary>
        public static string ExerciseForceType_Static {
            get {
                return ResourceManager.GetString("ExerciseForceType_Static", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shoulders.
        /// </summary>
        public static string ExerciseType_Barki {
            get {
                return ResourceManager.GetString("ExerciseType_Barki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biceps.
        /// </summary>
        public static string ExerciseType_Biceps {
            get {
                return ResourceManager.GetString("ExerciseType_Biceps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abs.
        /// </summary>
        public static string ExerciseType_Brzuch {
            get {
                return ResourceManager.GetString("ExerciseType_Brzuch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cardio.
        /// </summary>
        public static string ExerciseType_Cardio {
            get {
                return ResourceManager.GetString("ExerciseType_Cardio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traps.
        /// </summary>
        public static string ExerciseType_Czworoboczny {
            get {
                return ResourceManager.GetString("ExerciseType_Czworoboczny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chest.
        /// </summary>
        public static string ExerciseType_Klatka {
            get {
                return ResourceManager.GetString("ExerciseType_Klatka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calves.
        /// </summary>
        public static string ExerciseType_Lydki {
            get {
                return ResourceManager.GetString("ExerciseType_Lydki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hamstrings.
        /// </summary>
        public static string ExerciseType_Nogi {
            get {
                return ResourceManager.GetString("ExerciseType_Nogi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Deleted).
        /// </summary>
        public static string ExerciseType_NotSet {
            get {
                return ResourceManager.GetString("ExerciseType_NotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string ExerciseType_Plecy {
            get {
                return ResourceManager.GetString("ExerciseType_Plecy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forearm.
        /// </summary>
        public static string ExerciseType_Przedramie {
            get {
                return ResourceManager.GetString("ExerciseType_Przedramie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Triceps.
        /// </summary>
        public static string ExerciseType_Triceps {
            get {
                return ResourceManager.GetString("ExerciseType_Triceps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string Gender_Female {
            get {
                return ResourceManager.GetString("Gender_Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string Gender_Male {
            get {
                return ResourceManager.GetString("Gender_Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Not set).
        /// </summary>
        public static string Gender_NotSet {
            get {
                return ResourceManager.GetString("Gender_NotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only remap.
        /// </summary>
        public static string MapperEntryOperation_OnlyReMap {
            get {
                return ResourceManager.GetString("MapperEntryOperation_OnlyReMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remap and delete the source.
        /// </summary>
        public static string MapperEntryOperation_ReMapAndDeleteExercise {
            get {
                return ResourceManager.GetString("MapperEntryOperation_ReMapAndDeleteExercise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compound.
        /// </summary>
        public static string MechanicsType_Compound {
            get {
                return ResourceManager.GetString("MechanicsType_Compound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Isolation.
        /// </summary>
        public static string MechanicsType_Isolation {
            get {
                return ResourceManager.GetString("MechanicsType_Isolation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Not set).
        /// </summary>
        public static string MechanicsType_NotSet {
            get {
                return ResourceManager.GetString("MechanicsType_NotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string PictureCriteria_All {
            get {
                return ResourceManager.GetString("PictureCriteria_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only without photo.
        /// </summary>
        public static string PictureCriteria_OnlyWithoutPicture {
            get {
                return ResourceManager.GetString("PictureCriteria_OnlyWithoutPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only with photo.
        /// </summary>
        public static string PictureCriteria_OnlyWithPicture {
            get {
                return ResourceManager.GetString("PictureCriteria_OnlyWithPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only for friends.
        /// </summary>
        public static string Privacy_FriendsOnly {
            get {
                return ResourceManager.GetString("Privacy_FriendsOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private.
        /// </summary>
        public static string Privacy_Private {
            get {
                return ResourceManager.GetString("Privacy_Private", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public.
        /// </summary>
        public static string Privacy_Public {
            get {
                return ResourceManager.GetString("Privacy_Public", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only the available.
        /// </summary>
        public static string PrivacyCriteria_Accessible {
            get {
                return ResourceManager.GetString("PrivacyCriteria_Accessible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string PrivacyCriteria_All {
            get {
                return ResourceManager.GetString("PrivacyCriteria_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only the unavailable.
        /// </summary>
        public static string PrivacyCriteria_NotAccessible {
            get {
                return ResourceManager.GetString("PrivacyCriteria_NotAccessible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show this entry in your reports.
        /// </summary>
        public static string ReportStatus_ShowInReport {
            get {
                return ResourceManager.GetString("ReportStatus_ShowInReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not show this entry in your reports.
        /// </summary>
        public static string ReportStatus_SkipInReport {
            get {
                return ResourceManager.GetString("ReportStatus_SkipInReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max.
        /// </summary>
        public static string SetType_Max {
            get {
                return ResourceManager.GetString("SetType_Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muscle failure.
        /// </summary>
        public static string SetType_MuscleFailure {
            get {
                return ResourceManager.GetString("SetType_MuscleFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        public static string SetType_Normalna {
            get {
                return ResourceManager.GetString("SetType_Normalna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Almost max.
        /// </summary>
        public static string SetType_PrawieMax {
            get {
                return ResourceManager.GetString("SetType_PrawieMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warm-up.
        /// </summary>
        public static string SetType_Rozgrzewkowa {
            get {
                return ResourceManager.GetString("SetType_Rozgrzewkowa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopped.
        /// </summary>
        public static string TrainingEnd_Break {
            get {
                return ResourceManager.GetString("TrainingEnd_Break", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        public static string TrainingEnd_Complete {
            get {
                return ResourceManager.GetString("TrainingEnd_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In progress.
        /// </summary>
        public static string TrainingEnd_NotEnded {
            get {
                return ResourceManager.GetString("TrainingEnd_NotEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        public static string TrainingPlanDifficult_Advanced {
            get {
                return ResourceManager.GetString("TrainingPlanDifficult_Advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beginner.
        /// </summary>
        public static string TrainingPlanDifficult_Beginner {
            get {
                return ResourceManager.GetString("TrainingPlanDifficult_Beginner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Not set).
        /// </summary>
        public static string TrainingPlanDifficult_NotSet {
            get {
                return ResourceManager.GetString("TrainingPlanDifficult_NotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Professional.
        /// </summary>
        public static string TrainingPlanDifficult_Professional {
            get {
                return ResourceManager.GetString("TrainingPlanDifficult_Professional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorites.
        /// </summary>
        public static string UserSearchGroup_Favorites {
            get {
                return ResourceManager.GetString("UserSearchGroup_Favorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friends.
        /// </summary>
        public static string UserSearchGroup_Friends {
            get {
                return ResourceManager.GetString("UserSearchGroup_Friends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Others.
        /// </summary>
        public static string UserSearchGroup_Others {
            get {
                return ResourceManager.GetString("UserSearchGroup_Others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By number of blog comments.
        /// </summary>
        public static string UsersSortOrder_ByBlogCommentsCount {
            get {
                return ResourceManager.GetString("UsersSortOrder_ByBlogCommentsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By number of followers.
        /// </summary>
        public static string UsersSortOrder_ByFollowersCount {
            get {
                return ResourceManager.GetString("UsersSortOrder_ByFollowersCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By number of friends.
        /// </summary>
        public static string UsersSortOrder_ByFriendsCount {
            get {
                return ResourceManager.GetString("UsersSortOrder_ByFriendsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By date of last calendar&apos;s entry.
        /// </summary>
        public static string UsersSortOrder_ByLastEntryDate {
            get {
                return ResourceManager.GetString("UsersSortOrder_ByLastEntryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By date of last login.
        /// </summary>
        public static string UsersSortOrder_ByLastLoginDate {
            get {
                return ResourceManager.GetString("UsersSortOrder_ByLastLoginDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By name.
        /// </summary>
        public static string UsersSortOrder_ByName {
            get {
                return ResourceManager.GetString("UsersSortOrder_ByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By number of calendar entries.
        /// </summary>
        public static string UsersSortOrder_ByTrainingDaysCount {
            get {
                return ResourceManager.GetString("UsersSortOrder_ByTrainingDaysCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By number of voted items.
        /// </summary>
        public static string UsersSortOrder_ByVotingCount {
            get {
                return ResourceManager.GetString("UsersSortOrder_ByVotingCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By number of workout plans.
        /// </summary>
        public static string UsersSortOrder_ByWorkoutPlansCount {
            get {
                return ResourceManager.GetString("UsersSortOrder_ByWorkoutPlansCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A6W entries: {0}.
        /// </summary>
        public static string UserStatistics_A6WEntriesCount {
            get {
                return ResourceManager.GetString("UserStatistics_A6WEntriesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A6W cycles finished: {0}.
        /// </summary>
        public static string UserStatistics_A6WFullCyclesCount {
            get {
                return ResourceManager.GetString("UserStatistics_A6WFullCyclesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blog entries: {0}.
        /// </summary>
        public static string UserStatistics_BlogEntriesCount {
            get {
                return ResourceManager.GetString("UserStatistics_BlogEntriesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last entry: {0}.
        /// </summary>
        public static string UserStatistics_LastEntryDate {
            get {
                return ResourceManager.GetString("UserStatistics_LastEntryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last login: {0}.
        /// </summary>
        public static string UserStatistics_LastLoginDate {
            get {
                return ResourceManager.GetString("UserStatistics_LastLoginDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Next available status {0} requires {1} items..
        /// </summary>
        public static string UserStatistics_NextAvailableStatus_ToolTip {
            get {
                return ResourceManager.GetString("UserStatistics_NextAvailableStatus_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No status in this category. To achieve {0} status, {1} items are required..
        /// </summary>
        public static string UserStatistics_NoStatus_Description_ToolTip {
            get {
                return ResourceManager.GetString("UserStatistics_NoStatus_Description_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measurement entries: {0}.
        /// </summary>
        public static string UserStatistics_SizeEntriesCount {
            get {
                return ResourceManager.GetString("UserStatistics_SizeEntriesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: Current status achieved after {1} items in this category.{2}.
        /// </summary>
        public static string UserStatistics_Status_Description_ToolTip {
            get {
                return ResourceManager.GetString("UserStatistics_Status_Description_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplement entries: {0}.
        /// </summary>
        public static string UserStatistics_SupplementsEntriesCount {
            get {
                return ResourceManager.GetString("UserStatistics_SupplementsEntriesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string UserWorkoutPlanCriteria_All {
            get {
                return ResourceManager.GetString("UserWorkoutPlanCriteria_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only with public workout plans.
        /// </summary>
        public static string UserWorkoutPlanCriteria_OnlyWithWorkoutPlans {
            get {
                return ResourceManager.GetString("UserWorkoutPlanCriteria_OnlyWithWorkoutPlans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Definition.
        /// </summary>
        public static string WorkoutPlanPurpose_Definition {
            get {
                return ResourceManager.GetString("WorkoutPlanPurpose_Definition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fat lost.
        /// </summary>
        public static string WorkoutPlanPurpose_FatLost {
            get {
                return ResourceManager.GetString("WorkoutPlanPurpose_FatLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muscle mass.
        /// </summary>
        public static string WorkoutPlanPurpose_Mass {
            get {
                return ResourceManager.GetString("WorkoutPlanPurpose_Mass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Not set).
        /// </summary>
        public static string WorkoutPlanPurpose_NotSet {
            get {
                return ResourceManager.GetString("WorkoutPlanPurpose_NotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string WorkoutPlanPurpose_Other {
            get {
                return ResourceManager.GetString("WorkoutPlanPurpose_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strength.
        /// </summary>
        public static string WorkoutPlanPurpose_Strength {
            get {
                return ResourceManager.GetString("WorkoutPlanPurpose_Strength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Rated.
        /// </summary>
        public static string WorkoutPlanSearchOrder_HighestRating {
            get {
                return ResourceManager.GetString("WorkoutPlanSearchOrder_HighestRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest.
        /// </summary>
        public static string WorkoutPlanSearchOrder_Newest {
            get {
                return ResourceManager.GetString("WorkoutPlanSearchOrder_Newest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chest.
        /// </summary>
        public static string Wymiary_Chest {
            get {
                return ResourceManager.GetString("Wymiary_Chest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        public static string Wymiary_Height {
            get {
                return ResourceManager.GetString("Wymiary_Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left biceps.
        /// </summary>
        public static string Wymiary_LeftBiceps {
            get {
                return ResourceManager.GetString("Wymiary_LeftBiceps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left forearm.
        /// </summary>
        public static string Wymiary_LeftForearm {
            get {
                return ResourceManager.GetString("Wymiary_LeftForearm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left leg.
        /// </summary>
        public static string Wymiary_LeftUdo {
            get {
                return ResourceManager.GetString("Wymiary_LeftUdo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waist.
        /// </summary>
        public static string Wymiary_Pas {
            get {
                return ResourceManager.GetString("Wymiary_Pas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right biceps.
        /// </summary>
        public static string Wymiary_RightBiceps {
            get {
                return ResourceManager.GetString("Wymiary_RightBiceps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right forearm.
        /// </summary>
        public static string Wymiary_RightForearm {
            get {
                return ResourceManager.GetString("Wymiary_RightForearm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right leg.
        /// </summary>
        public static string Wymiary_RightUdo {
            get {
                return ResourceManager.GetString("Wymiary_RightUdo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight.
        /// </summary>
        public static string Wymiary_Weight {
            get {
                return ResourceManager.GetString("Wymiary_Weight", resourceCulture);
            }
        }
    }
}
