//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BodyArchitect.Controls.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SuperTips {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SuperTips() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BodyArchitect.Controls.Localization.SuperTips", typeof(SuperTips).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry date. If the entry contains session training, then this is the training date..
        /// </summary>
        internal static string AddTrainingDay_DateTE {
            get {
                return ResourceManager.GetString("AddTrainingDay_DateTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is your body mass index (BMI):
        ///
        ///Severely underweight - less than 16.5
        ///Underweight - from 16.5 to 18.4
        ///Normal - from 18.5 to 24.9
        ///Overweight - from 25 to 29.9
        ///Obese Class I - from 30 to 34.9
        ///Obese Class II - from 35 to 39.9
        ///Obese Class III - over 40.
        /// </summary>
        internal static string BMI_BMI {
            get {
                return ResourceManager.GetString("BMI_BMI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to calculate your BMI. You have to type your weight and height first..
        /// </summary>
        internal static string BMI_Calculate {
            get {
                return ResourceManager.GetString("BMI_Calculate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closes this window.
        /// </summary>
        internal static string BMI_Close {
            get {
                return ResourceManager.GetString("BMI_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type your height in cm.
        /// </summary>
        internal static string BMI_Height {
            get {
                return ResourceManager.GetString("BMI_Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type your weight in kg.
        /// </summary>
        internal static string BMI_Weight {
            get {
                return ResourceManager.GetString("BMI_Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saves changes without closing the window..
        /// </summary>
        internal static string ButtonApply {
            get {
                return ResourceManager.GetString("ButtonApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejects changes and close the window..
        /// </summary>
        internal static string ButtonCancel {
            get {
                return ResourceManager.GetString("ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete the current entry..
        /// </summary>
        internal static string ButtonDelete {
            get {
                return ResourceManager.GetString("ButtonDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saves changes and close the window..
        /// </summary>
        internal static string ButtonOK {
            get {
                return ResourceManager.GetString("ButtonOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When selected means that when we start the application, this profile will be logged automatically..
        /// </summary>
        internal static string CreateProfile_Autologin_CHK {
            get {
                return ResourceManager.GetString("CreateProfile_Autologin_CHK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile name will be used during login to the application. Must be unique..
        /// </summary>
        internal static string CreateProfile_NameTE {
            get {
                return ResourceManager.GetString("CreateProfile_NameTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is used to prevent access to your profile. It is not required. When there is only one profile without password in the application, then it will be used automatically when application starts (without login)..
        /// </summary>
        internal static string CreateProfile_PasswordTE {
            get {
                return ResourceManager.GetString("CreateProfile_PasswordTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starts importing default data to the current profile. TO choose what data you want to import, please selected one or more items in the list..
        /// </summary>
        internal static string DefaultDataImporter_ImportBTN {
            get {
                return ResourceManager.GetString("DefaultDataImporter_ImportBTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of all available data to import. To import data you need to select appropriate item in this list and press Import... button. .
        /// </summary>
        internal static string DefaultDataImporter_ModulesListView {
            get {
                return ResourceManager.GetString("DefaultDataImporter_ModulesListView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When selected means that when we start the application, this profile will be logged automatically..
        /// </summary>
        internal static string Login_AutologinCHK {
            get {
                return ResourceManager.GetString("Login_AutologinCHK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile name from the program&apos;s database..
        /// </summary>
        internal static string Login_NameTE {
            get {
                return ResourceManager.GetString("Login_NameTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password for the selected profile..
        /// </summary>
        internal static string Login_PasswordTE {
            get {
                return ResourceManager.GetString("Login_PasswordTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you can set options related with each module in BodyArchitect:
        ///&lt;b&gt;Icon&lt;/b&gt; - if selected then entry for this plugin will be shown in calendar view as icon
        ///&lt;b&gt;Default&lt;/b&gt; - if selected then entry for this plugin will be automatically added when you create a new entry day in the calendar view.
        /// </summary>
        internal static string OptionCalendarIcons {
            get {
                return ResourceManager.GetString("OptionCalendarIcons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If checked, the dates in the application (for example comment date or last login date) will be displayed as relative date from current moment, like: 2 minutes ago, 5 months ago, etc. If unchecked then you see specific date..
        /// </summary>
        internal static string OptionCalendarShowRelativeDates {
            get {
                return ResourceManager.GetString("OptionCalendarShowRelativeDates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows options for calendar view.
        /// </summary>
        internal static string OptionCalendarTabPage {
            get {
                return ResourceManager.GetString("OptionCalendarTabPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates from what plugin calendar view will show info text.
        /// </summary>
        internal static string OptionCalendarTextFrom {
            get {
                return ResourceManager.GetString("OptionCalendarTextFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If selected, you can zoom reports..
        /// </summary>
        internal static string OptionReportingAllowZoom {
            get {
                return ResourceManager.GetString("OptionReportingAllowZoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If selected, on reports you will see values as labels, otherwise reports will only display lines..
        /// </summary>
        internal static string OptionReportingShowValues {
            get {
                return ResourceManager.GetString("OptionReportingShowValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of all templates (themes) for reporting view..
        /// </summary>
        internal static string OptionReportingTemplates {
            get {
                return ResourceManager.GetString("OptionReportingTemplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resets all settings to default values..
        /// </summary>
        internal static string OptionResetAllBtn {
            get {
                return ResourceManager.GetString("OptionResetAllBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthday. Can be empty..
        /// </summary>
        internal static string ProfileEdit_BirthdayTE {
            get {
                return ResourceManager.GetString("ProfileEdit_BirthdayTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows you to specify your gender. This information is needed to use some of calculators (for instance BMI).
        /// </summary>
        internal static string ProfileEdit_GenderCMB {
            get {
                return ResourceManager.GetString("ProfileEdit_GenderCMB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of edited profile. Must be unique..
        /// </summary>
        internal static string ProfileEdit_NameTE {
            get {
                return ResourceManager.GetString("ProfileEdit_NameTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you are able to define starting date for you report. All entries which are older will not be shown..
        /// </summary>
        internal static string usrDateRange_DateFrom {
            get {
                return ResourceManager.GetString("usrDateRange_DateFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you are able to define end date for you report. All newer entries will not be shown..
        /// </summary>
        internal static string usrDateRange_DateTo {
            get {
                return ResourceManager.GetString("usrDateRange_DateTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to abort (stop) this training cycle. You will not be able to resume this cycle again..
        /// </summary>
        internal static string usrMyTrainingStatus_Abort {
            get {
                return ResourceManager.GetString("usrMyTrainingStatus_Abort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date when this training cycle has been finished..
        /// </summary>
        internal static string usrMyTrainingStatus_EndDate {
            get {
                return ResourceManager.GetString("usrMyTrainingStatus_EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date when this training cycle has been started..
        /// </summary>
        internal static string usrMyTrainingStatus_StartDate {
            get {
                return ResourceManager.GetString("usrMyTrainingStatus_StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates what entries will be used to generate the report. Select
        ///-&lt;b&gt;For report only&lt;/b&gt; when you want to generate report with entries with ReportStatus &lt;b&gt;Show this entry in reports&lt;/b&gt; only. 
        ///-&lt;b&gt;All entries&lt;/b&gt; to generate report with all entries (also with ReportStatus &lt;b&gt;Skip this entry in reports&lt;/b&gt;.
        /// </summary>
        internal static string usrReportingEntryStatus_ReportStatusCmb {
            get {
                return ResourceManager.GetString("usrReportingEntryStatus_ReportStatusCmb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates if current entry will be used in reports. Value Show means that you will see this entry in reports, value Skip means, that reports will not use it..
        /// </summary>
        internal static string usrReportStatus_ReportStatusCmb {
            get {
                return ResourceManager.GetString("usrReportStatus_ReportStatusCmb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height in cm, e.g. 188. Value 0 means that height was not set..
        /// </summary>
        internal static string WymiaryEditor_Height {
            get {
                return ResourceManager.GetString("WymiaryEditor_Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chest circumference, e.g. 110,5. Value 0 means that chest circumference was not set..
        /// </summary>
        internal static string WymiaryEditor_Klatka {
            get {
                return ResourceManager.GetString("WymiaryEditor_Klatka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left biceps circumference, e.g. 37,5. Value 0 means that biceps circumference was not set..
        /// </summary>
        internal static string WymiaryEditor_LeftBiceps {
            get {
                return ResourceManager.GetString("WymiaryEditor_LeftBiceps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left forearm circumference, e.g. 27,5. Value 0 means that forearm circumference was not set..
        /// </summary>
        internal static string WymiaryEditor_LeftForearm {
            get {
                return ResourceManager.GetString("WymiaryEditor_LeftForearm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left leg circumference, e.g. 67,5. Value 0 means that leg circumference was not set..
        /// </summary>
        internal static string WymiaryEditor_LeftLeg {
            get {
                return ResourceManager.GetString("WymiaryEditor_LeftLeg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected means that all measurements was made on empty stomach..
        /// </summary>
        internal static string WymiaryEditor_NaCzczo {
            get {
                return ResourceManager.GetString("WymiaryEditor_NaCzczo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abs circumference, e.g. 77,5. Value 0 means that abs circumference was not set..
        /// </summary>
        internal static string WymiaryEditor_Pas {
            get {
                return ResourceManager.GetString("WymiaryEditor_Pas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right biceps circumference, e.g. 37,5. Value 0 means that biceps circumference was not set..
        /// </summary>
        internal static string WymiaryEditor_RightBiceps {
            get {
                return ResourceManager.GetString("WymiaryEditor_RightBiceps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right forearm circumference, e.g. 27,5. Value 0 means that forearm circumference was not set..
        /// </summary>
        internal static string WymiaryEditor_RightForearm {
            get {
                return ResourceManager.GetString("WymiaryEditor_RightForearm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right leg circumference, e.g. 67,5. Value 0 means that leg circumference was not set..
        /// </summary>
        internal static string WymiaryEditor_RightLeg {
            get {
                return ResourceManager.GetString("WymiaryEditor_RightLeg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time of measurement, e.g: 7:05. Value 00:00 means that time was not set..
        /// </summary>
        internal static string WymiaryEditor_Time {
            get {
                return ResourceManager.GetString("WymiaryEditor_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight in kilograms, e.g. 81,5. Value 0 means that weight was not set..
        /// </summary>
        internal static string WymiaryEditor_Weight {
            get {
                return ResourceManager.GetString("WymiaryEditor_Weight", resourceCulture);
            }
        }
    }
}
