//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BodyArchitect.Client.Module.Measurements {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SizeEntryStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SizeEntryStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BodyArchitect.Client.Module.Measurements.SizeEntryStrings", typeof(SizeEntryStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measurements.
        /// </summary>
        internal static string EntryTypeName {
            get {
                return ResourceManager.GetString("EntryTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short description of measurements entry.
        /// </summary>
        internal static string EntryTypeShortDescription {
            get {
                return ResourceManager.GetString("EntryTypeShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measurements.
        /// </summary>
        internal static string MeasurementsCalendarDayContent {
            get {
                return ResourceManager.GetString("MeasurementsCalendarDayContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If selected, when you add size entry then automatically your profile&apos;s measurements will be updated..
        /// </summary>
        internal static string Option_Tip_UpdateProfileSizes {
            get {
                return ResourceManager.GetString("Option_Tip_UpdateProfileSizes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measurements module.
        /// </summary>
        internal static string OptionsSizeTitle {
            get {
                return ResourceManager.GetString("OptionsSizeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes in measurements in time.
        /// </summary>
        internal static string Report_SizesTime_Name {
            get {
                return ResourceManager.GetString("Report_SizesTime_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        internal static string Report_SizeTime_AxisXTitle {
            get {
                return ResourceManager.GetString("Report_SizeTime_AxisXTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measurement.
        /// </summary>
        internal static string Report_SizeTime_AxisYTitle {
            get {
                return ResourceManager.GetString("Report_SizeTime_AxisYTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} &lt;i&gt;{1:.##}{2}&lt;/i&gt;&lt;br/&gt;.
        /// </summary>
        internal static string SizeModule_addMeasurement {
            get {
                return ResourceManager.GetString("SizeModule_addMeasurement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BodyArchitect - workout log and social application created for professional bodybuilders..
        /// </summary>
        internal static string SizeModule_ShareToSocial_Caption {
            get {
                return ResourceManager.GetString("SizeModule_ShareToSocial_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date: {0}&lt;br/&gt;&lt;br/&gt;.
        /// </summary>
        internal static string SizeModule_ShareToSocial_Date {
            get {
                return ResourceManager.GetString("SizeModule_ShareToSocial_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New entry: Measurements.
        /// </summary>
        internal static string SizeModule_ShareToSocial_Name {
            get {
                return ResourceManager.GetString("SizeModule_ShareToSocial_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Put some comment about this measurements.
        /// </summary>
        internal static string usrMeasurementsEntry_Comment_Watermark {
            get {
                return ResourceManager.GetString("usrMeasurementsEntry_Comment_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        internal static string usrMeasurementsEntry_Header_Comment {
            get {
                return ResourceManager.GetString("usrMeasurementsEntry_Header_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remind.
        /// </summary>
        internal static string usrMeasurementsEntry_Header_Remind {
            get {
                return ResourceManager.GetString("usrMeasurementsEntry_Header_Remind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of all measurements you can use to generate a report..
        /// </summary>
        internal static string usrSizesTimeReport_ListView {
            get {
                return ResourceManager.GetString("usrSizesTimeReport_ListView", resourceCulture);
            }
        }
    }
}
