//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.208
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BodyArchitect.Module.Suplements {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SuplementsEntryStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SuplementsEntryStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BodyArchitect.Module.Suplements.SuplementsEntryStrings", typeof(SuplementsEntryStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string ColumnSuplementName {
            get {
                return ResourceManager.GetString("ColumnSuplementName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplement types.
        /// </summary>
        public static string DefaultSuplementsName {
            get {
                return ResourceManager.GetString("DefaultSuplementsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete this entry.
        /// </summary>
        public static string DeleteThisEntryTip {
            get {
                return ResourceManager.GetString("DeleteThisEntryTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplements.
        /// </summary>
        public static string EntryTypeName {
            get {
                return ResourceManager.GetString("EntryTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete selected supplement types. Please see the log file. ErrorId: {0}..
        /// </summary>
        public static string ErrorCannotDeleteSuplementType {
            get {
                return ResourceManager.GetString("ErrorCannotDeleteSuplementType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred during saving..
        /// </summary>
        public static string ErrorDuringSuplementSaving {
            get {
                return ResourceManager.GetString("ErrorDuringSuplementSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to remove selected row?.
        /// </summary>
        public static string QDeleteSuplementRow {
            get {
                return ResourceManager.GetString("QDeleteSuplementRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete selected supplement types?.
        /// </summary>
        public static string QDeleteSuplementType {
            get {
                return ResourceManager.GetString("QDeleteSuplementType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Select a supplement type).
        /// </summary>
        public static string SelectSuplementType {
            get {
                return ResourceManager.GetString("SelectSuplementType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suplement name cannot be empty..
        /// </summary>
        public static string Suplement_Name_Empty {
            get {
                return ResourceManager.GetString("Suplement_Name_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suplement name is too long..
        /// </summary>
        public static string Suplement_Name_Length {
            get {
                return ResourceManager.GetString("Suplement_Name_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suplement name must be unique..
        /// </summary>
        public static string Suplement_Name_Unique {
            get {
                return ResourceManager.GetString("Suplement_Name_Unique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dosage.
        /// </summary>
        public static string SuplementGrid_DosageColumn {
            get {
                return ResourceManager.GetString("SuplementGrid_DosageColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dosage type.
        /// </summary>
        public static string SuplementGrid_DosageTypeColumn {
            get {
                return ResourceManager.GetString("SuplementGrid_DosageTypeColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string SuplementGrid_InfoColumn {
            get {
                return ResourceManager.GetString("SuplementGrid_InfoColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string SuplementGrid_NameColumn {
            get {
                return ResourceManager.GetString("SuplementGrid_NameColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplement.
        /// </summary>
        public static string SuplementGrid_SuplementColumn {
            get {
                return ResourceManager.GetString("SuplementGrid_SuplementColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string SuplementGrid_TimeColumn {
            get {
                return ResourceManager.GetString("SuplementGrid_TimeColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows add a new supplement type to the database..
        /// </summary>
        public static string SuplementsViewWindow_AddBTN {
            get {
                return ResourceManager.GetString("SuplementsViewWindow_AddBTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deletes selected supplement types permanently..
        /// </summary>
        public static string SuplementsViewWindow_DeleteBTN {
            get {
                return ResourceManager.GetString("SuplementsViewWindow_DeleteBTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows edit selected supplement type..
        /// </summary>
        public static string SuplementsViewWindow_EditBTN {
            get {
                return ResourceManager.GetString("SuplementsViewWindow_EditBTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of all supplement types in the database..
        /// </summary>
        public static string SuplementsViewWindow_SuplementsListView {
            get {
                return ResourceManager.GetString("SuplementsViewWindow_SuplementsListView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional information about this supplement..
        /// </summary>
        public static string SuplementTypeEditor_CommentTXT {
            get {
                return ResourceManager.GetString("SuplementTypeEditor_CommentTXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of the supplement. Must be unique and cannot be empty..
        /// </summary>
        public static string SuplementTypeEditor_NameTXT {
            get {
                return ResourceManager.GetString("SuplementTypeEditor_NameTXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplement types....
        /// </summary>
        public static string SuplementTypesMenu {
            get {
                return ResourceManager.GetString("SuplementTypesMenu", resourceCulture);
            }
        }
    }
}
