//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BodyArchitect.Client.Module.A6W.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class A6WEntryStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal A6WEntryStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BodyArchitect.Client.Module.A6W.Localization.A6WEntryStrings", typeof(A6WEntryStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional informations about the current training session.
        /// </summary>
        public static string A6W_CommentTXT {
            get {
                return ResourceManager.GetString("A6W_CommentTXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select it if you&apos;ve made all required sets and repetitions..
        /// </summary>
        public static string A6W_CompletedRB {
            get {
                return ResourceManager.GetString("A6W_CompletedRB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every position in this list represents one day in A6W training plan. You can see how many sets and reps every day contains. If the list position (a day) has an icon that this means that this day has been completed..
        /// </summary>
        public static string A6W_LV {
            get {
                return ResourceManager.GetString("A6W_LV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select it if you&apos;ve finished the current day but you didn&apos;t do all required sets or repetitions. Additionally you can type repetitions number below..
        /// </summary>
        public static string A6W_PartialCompletedRB {
            get {
                return ResourceManager.GetString("A6W_PartialCompletedRB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you did less than required you can type how many repetitions you did..
        /// </summary>
        public static string A6W_PartialCompleteSet {
            get {
                return ResourceManager.GetString("A6W_PartialCompleteSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A6W.
        /// </summary>
        public static string A6WCalendarDayContentName {
            get {
                return ResourceManager.GetString("A6WCalendarDayContentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A6W.
        /// </summary>
        public static string A6WModule_CreateRibbonGroup_Header {
            get {
                return ResourceManager.GetString("A6WModule_CreateRibbonGroup_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start A6W.
        /// </summary>
        public static string A6WModule_CreateRibbonGroup_Label {
            get {
                return ResourceManager.GetString("A6WModule_CreateRibbonGroup_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BodyArchitect - workout log and social application created for professional bodybuilders..
        /// </summary>
        public static string A6WModule_ShareToSocial_Caption {
            get {
                return ResourceManager.GetString("A6WModule_ShareToSocial_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;br/&gt;&lt;b&gt;Day {0} completed&lt;/b&gt;&lt;br/&gt;Date: {1}&lt;br/&gt;&lt;br/&gt;Whole A6W training is finished. Congratulations!..
        /// </summary>
        public static string A6WModule_ShareToSocial_Finished_Description {
            get {
                return ResourceManager.GetString("A6WModule_ShareToSocial_Finished_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New entry: Aerobic Weider&apos;s &quot;6&quot;.
        /// </summary>
        public static string A6WModule_ShareToSocial_Name {
            get {
                return ResourceManager.GetString("A6WModule_ShareToSocial_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;br/&gt;&lt;big&gt;&lt;b&gt;Day {0} completed&lt;/b&gt;&lt;/big&gt;&lt;br/&gt;Date: {1}&lt;br/&gt;&lt;br/&gt;There are {2} days left to finish this training..
        /// </summary>
        public static string A6WModule_ShareToSocial_NotFinished_Description {
            get {
                return ResourceManager.GetString("A6WModule_ShareToSocial_NotFinished_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day {0}.
        /// </summary>
        public static string CalendarDayText {
            get {
                return ResourceManager.GetString("CalendarDayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A6W.
        /// </summary>
        public static string EntryTypeName {
            get {
                return ResourceManager.GetString("EntryTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very hard training for your ABS.
        /// </summary>
        public static string EntryTypeShortDescription {
            get {
                return ResourceManager.GetString("EntryTypeShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to select result for this day (Completed or Partial completed)..
        /// </summary>
        public static string ErrorA6WDayResultMissing {
            get {
                return ResourceManager.GetString("ErrorA6WDayResultMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A6W training is already started. You need to finish is first..
        /// </summary>
        public static string ErrorA6WTrainingAlreadyStarted {
            get {
                return ResourceManager.GetString("ErrorA6WTrainingAlreadyStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have entered to many repetitions for set {0}. To complete day {1} you need to do {2} repetitions..
        /// </summary>
        public static string ErrorSetTooManyRepetitions {
            get {
                return ResourceManager.GetString("ErrorSetTooManyRepetitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot finish this operation because this would cause break training integrity..
        /// </summary>
        public static string ErrorTrainingIntegrity {
            get {
                return ResourceManager.GetString("ErrorTrainingIntegrity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot start A6W training.
        /// </summary>
        public static string ExceptionCannotStartA6WTraining {
            get {
                return ResourceManager.GetString("ExceptionCannotStartA6WTraining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        public static string StartA6WCycleWindow_Content_Preview {
            get {
                return ResourceManager.GetString("StartA6WCycleWindow_Content_Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date:.
        /// </summary>
        public static string StartA6WCycleWindow_Content_StartDate {
            get {
                return ResourceManager.GetString("StartA6WCycleWindow_Content_StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters.
        /// </summary>
        public static string StartA6WCycleWindow_Header_Parameters {
            get {
                return ResourceManager.GetString("StartA6WCycleWindow_Header_Parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        public static string StartA6WCycleWindow_Header_Preview {
            get {
                return ResourceManager.GetString("StartA6WCycleWindow_Header_Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string StartA6WCycleWindow_OKButton_Start {
            get {
                return ResourceManager.GetString("StartA6WCycleWindow_OKButton_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click the Preview button to see simulation of A6W training. No changes will be applied to your calendar..
        /// </summary>
        public static string StartA6WCycleWindow_Text_ClickPreviewButton {
            get {
                return ResourceManager.GetString("StartA6WCycleWindow_Text_ClickPreviewButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start a new training.
        /// </summary>
        public static string StartA6WCycleWindow_Title {
            get {
                return ResourceManager.GetString("StartA6WCycleWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a name of this training.
        /// </summary>
        public static string StartA6WCycleWindow_Watermark_EnterNameOfTraining {
            get {
                return ResourceManager.GetString("StartA6WCycleWindow_Watermark_EnterNameOfTraining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A6W training.
        /// </summary>
        public static string StartA6WViewModel_Name_A6WTraining {
            get {
                return ResourceManager.GetString("StartA6WViewModel_Name_A6WTraining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have completed A6W training. Congratulations.
        /// </summary>
        public static string TrainingCompletedText {
            get {
                return ResourceManager.GetString("TrainingCompletedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        public static string usrA6W_Content_Completed {
            get {
                return ResourceManager.GetString("usrA6W_Content_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partial completed.
        /// </summary>
        public static string usrA6W_Content_PartialCompleted {
            get {
                return ResourceManager.GetString("usrA6W_Content_PartialCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string usrA6W_Header_Comment {
            get {
                return ResourceManager.GetString("usrA6W_Header_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string usrA6W_Header_Info {
            get {
                return ResourceManager.GetString("usrA6W_Header_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repetitions.
        /// </summary>
        public static string usrA6W_Header_Repetitions {
            get {
                return ResourceManager.GetString("usrA6W_Header_Repetitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets.
        /// </summary>
        public static string usrA6W_Header_Sets {
            get {
                return ResourceManager.GetString("usrA6W_Header_Sets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        public static string usrA6W_Header_Weeks {
            get {
                return ResourceManager.GetString("usrA6W_Header_Weeks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repetitions for set _1:.
        /// </summary>
        public static string usrA6WPartialCompleted_Reps1Label {
            get {
                return ResourceManager.GetString("usrA6WPartialCompleted_Reps1Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repetitions for set _2:.
        /// </summary>
        public static string usrA6WPartialCompleted_Reps2Label {
            get {
                return ResourceManager.GetString("usrA6WPartialCompleted_Reps2Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repetitions for set _3:.
        /// </summary>
        public static string usrA6WPartialCompleted_Reps3Label {
            get {
                return ResourceManager.GetString("usrA6WPartialCompleted_Reps3Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        public static string usrA6WProgress_Completed {
            get {
                return ResourceManager.GetString("usrA6WProgress_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not completed.
        /// </summary>
        public static string usrA6WProgress_NotCompleted {
            get {
                return ResourceManager.GetString("usrA6WProgress_NotCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A6W training.
        /// </summary>
        public static string usrA6WProgress_ReportTitle {
            get {
                return ResourceManager.GetString("usrA6WProgress_ReportTitle", resourceCulture);
            }
        }
    }
}
