//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17020
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BodyArchitect.Client.Module.Blog.Options {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class BlogSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static BlogSettings defaultInstance = ((BlogSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new BlogSettings())));
        
        public static BlogSettings Default {
            get {
                return defaultInstance;
            }
        }
    }
}
