//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.208
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BodyArchitect.Module.StrengthTraining.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LocalizedPropertyGridStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizedPropertyGridStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BodyArchitect.Module.StrengthTraining.Localization.LocalizedPropertyGridStrings", typeof(LocalizedPropertyGridStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exercise name cannot be empty..
        /// </summary>
        public static string Exercise_Name_Empty {
            get {
                return ResourceManager.GetString("Exercise_Name_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exercise name is too long..
        /// </summary>
        public static string Exercise_Name_Length {
            get {
                return ResourceManager.GetString("Exercise_Name_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exercise shortcut cannot be empty..
        /// </summary>
        public static string Exercise_Shortcut_Empty {
            get {
                return ResourceManager.GetString("Exercise_Shortcut_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exercise shortcut must be unique..
        /// </summary>
        public static string Exercise_Shortcut_Unique {
            get {
                return ResourceManager.GetString("Exercise_Shortcut_Unique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url is too long..
        /// </summary>
        public static string Exercise_Url_Length {
            get {
                return ResourceManager.GetString("Exercise_Url_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print options.
        /// </summary>
        public static string PrintOptions {
            get {
                return ResourceManager.GetString("PrintOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Isolation exercise is before compound exercises. In split workout you should first do compound exercises and then isolation..
        /// </summary>
        public static string Split_IsolationExerciseBeforeCompoud {
            get {
                return ResourceManager.GetString("Split_IsolationExerciseBeforeCompoud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must set Author name..
        /// </summary>
        public static string TrainingPlan_Author_Empty {
            get {
                return ResourceManager.GetString("TrainingPlan_Author_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author name of the workout plan is too long..
        /// </summary>
        public static string TrainingPlan_Author_Length {
            get {
                return ResourceManager.GetString("TrainingPlan_Author_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are Workout days with the same name. All days must have unique name.
        /// </summary>
        public static string TrainingPlan_DaysName_Unique {
            get {
                return ResourceManager.GetString("TrainingPlan_DaysName_Unique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop set usually is used only in the last set of the exercise..
        /// </summary>
        public static string TrainingPlan_DropSetInNotOnlyLastSet {
            get {
                return ResourceManager.GetString("TrainingPlan_DropSetInNotOnlyLastSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should add entries into workout day..
        /// </summary>
        public static string TrainingPlan_EmptyDay {
            get {
                return ResourceManager.GetString("TrainingPlan_EmptyDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exercise used in the workout plan doesn&apos;t exist or you didn&apos;t choose any..
        /// </summary>
        public static string TrainingPlan_ExerciseDoesntExist {
            get {
                return ResourceManager.GetString("TrainingPlan_ExerciseDoesntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workout plan must have a name..
        /// </summary>
        public static string TrainingPlan_Name_Empty {
            get {
                return ResourceManager.GetString("TrainingPlan_Name_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workout plan.
        /// </summary>
        public static string TrainingPlan_Object {
            get {
                return ResourceManager.GetString("TrainingPlan_Object", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should define rest time..
        /// </summary>
        public static string TrainingPlan_RestSecond_Empty {
            get {
                return ResourceManager.GetString("TrainingPlan_RestSecond_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workout plan day cannot have an empty Name..
        /// </summary>
        public static string TrainingPlanDay_Name_Empty {
            get {
                return ResourceManager.GetString("TrainingPlanDay_Name_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workout plan day name is too long..
        /// </summary>
        public static string TrainingPlanDay_Name_Length {
            get {
                return ResourceManager.GetString("TrainingPlanDay_Name_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workout day.
        /// </summary>
        public static string TrainingPlanDay_Object {
            get {
                return ResourceManager.GetString("TrainingPlanDay_Object", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workout day entry.
        /// </summary>
        public static string TrainingPlanDayEntry_Object {
            get {
                return ResourceManager.GetString("TrainingPlanDayEntry_Object", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set this to true to have a nice background after you print your workout plan.
        /// </summary>
        public static string TrainingPlanHtmlExporter_PrintBackground_Description {
            get {
                return ResourceManager.GetString("TrainingPlanHtmlExporter.PrintBackground.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print background.
        /// </summary>
        public static string TrainingPlanHtmlExporter_PrintBackground_DisplayName {
            get {
                return ResourceManager.GetString("TrainingPlanHtmlExporter.PrintBackground.DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you can decide which workout days you want to see in your plan..
        /// </summary>
        public static string TrainingPlanHtmlExporter_PrintDays_Description {
            get {
                return ResourceManager.GetString("TrainingPlanHtmlExporter.PrintDays.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days to print.
        /// </summary>
        public static string TrainingPlanHtmlExporter_PrintDays_DisplayName {
            get {
                return ResourceManager.GetString("TrainingPlanHtmlExporter.PrintDays.DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you can decide if you want to see workout plan description.
        /// </summary>
        public static string TrainingPlanHtmlExporter_PrintDescription_Description {
            get {
                return ResourceManager.GetString("TrainingPlanHtmlExporter.PrintDescription.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print description.
        /// </summary>
        public static string TrainingPlanHtmlExporter_PrintDescription_DisplayName {
            get {
                return ResourceManager.GetString("TrainingPlanHtmlExporter.PrintDescription.DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set this option to print entries comment..
        /// </summary>
        public static string TrainingPlanHtmlExporter_PrintEntriesComment_Description {
            get {
                return ResourceManager.GetString("TrainingPlanHtmlExporter.PrintEntriesComment.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print entries comment.
        /// </summary>
        public static string TrainingPlanHtmlExporter_PrintEntriesComment_DisplayName {
            get {
                return ResourceManager.GetString("TrainingPlanHtmlExporter.PrintEntriesComment.DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set this option to true to add exercise shortcut in the workout plan.
        /// </summary>
        public static string TrainingPlanHtmlExporter_PrintExerciseShortcut_Description {
            get {
                return ResourceManager.GetString("TrainingPlanHtmlExporter.PrintExerciseShortcut.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print exercise shortcut.
        /// </summary>
        public static string TrainingPlanHtmlExporter_PrintExerciseShortcut_DisplayName {
            get {
                return ResourceManager.GetString("TrainingPlanHtmlExporter.PrintExerciseShortcut.DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set this option to true to put main muscle for every exercise in the workout plan.
        /// </summary>
        public static string TrainingPlanHtmlExporter_PrintExerciseType_Description {
            get {
                return ResourceManager.GetString("TrainingPlanHtmlExporter.PrintExerciseType.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print muscle.
        /// </summary>
        public static string TrainingPlanHtmlExporter_PrintExerciseType_DisplayName {
            get {
                return ResourceManager.GetString("TrainingPlanHtmlExporter.PrintExerciseType.DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates if the headers of each section will be printed.
        /// </summary>
        public static string TrainingPlanHtmlExporter_PrintHeaders_Description {
            get {
                return ResourceManager.GetString("TrainingPlanHtmlExporter.PrintHeaders.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print headers.
        /// </summary>
        public static string TrainingPlanHtmlExporter_PrintHeaders_DisplayName {
            get {
                return ResourceManager.GetString("TrainingPlanHtmlExporter.PrintHeaders.DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you can decide if you want to see information panel.
        /// </summary>
        public static string TrainingPlanHtmlExporter_PrintInfo_Description {
            get {
                return ResourceManager.GetString("TrainingPlanHtmlExporter.PrintInfo.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print info.
        /// </summary>
        public static string TrainingPlanHtmlExporter_PrintInfo_DisplayName {
            get {
                return ResourceManager.GetString("TrainingPlanHtmlExporter.PrintInfo.DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set this option to print the legend (description about what you see in the workout plan).
        /// </summary>
        public static string TrainingPlanHtmlExporter_PrintLegend_Description {
            get {
                return ResourceManager.GetString("TrainingPlanHtmlExporter.PrintLegend.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print the legend.
        /// </summary>
        public static string TrainingPlanHtmlExporter_PrintLegend_DisplayName {
            get {
                return ResourceManager.GetString("TrainingPlanHtmlExporter.PrintLegend.DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This setting is related with sets number. If you select this options then in your workout plan you will see only required sets. If you set false, then you will see all sets defined in sets number property..
        /// </summary>
        public static string TrainingPlanHtmlExporter_PrintRequiredSetsOnly_Description {
            get {
                return ResourceManager.GetString("TrainingPlanHtmlExporter.PrintRequiredSetsOnly.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print only required sets.
        /// </summary>
        public static string TrainingPlanHtmlExporter_PrintRequiredSetsOnly_DisplayName {
            get {
                return ResourceManager.GetString("TrainingPlanHtmlExporter.PrintRequiredSetsOnly.DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set this option to print all comment for every set (if available).
        /// </summary>
        public static string TrainingPlanHtmlExporter_PrintSetsComment_Description {
            get {
                return ResourceManager.GetString("TrainingPlanHtmlExporter.PrintSetsComment.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print sets&apos; comment.
        /// </summary>
        public static string TrainingPlanHtmlExporter_PrintSetsComment_DisplayName {
            get {
                return ResourceManager.GetString("TrainingPlanHtmlExporter.PrintSetsComment.DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This option is good for print workout plan when you go to the gym. When this option is set to true, in the workout plan in every set you will have a place to put your own values..
        /// </summary>
        public static string TrainingPlanHtmlExporter_PrintSetsPlaceholders_Description {
            get {
                return ResourceManager.GetString("TrainingPlanHtmlExporter.PrintSetsPlaceholders.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print sets placeholders.
        /// </summary>
        public static string TrainingPlanHtmlExporter_PrintSetsPlaceholders_DisplayName {
            get {
                return ResourceManager.GetString("TrainingPlanHtmlExporter.PrintSetsPlaceholders.DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This setting is related with Print required sets only. It determines how many sets you will see in the workout plan..
        /// </summary>
        public static string TrainingPlanHtmlExporter_SetsNumberToPrint_Description {
            get {
                return ResourceManager.GetString("TrainingPlanHtmlExporter.SetsNumberToPrint.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets number to print.
        /// </summary>
        public static string TrainingPlanHtmlExporter_SetsNumberToPrint_DisplayName {
            get {
                return ResourceManager.GetString("TrainingPlanHtmlExporter.SetsNumberToPrint.DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set this option to true to highlight exercises row to increase usability..
        /// </summary>
        public static string TrainingPlanHtmlExporter_UseAlternateRows_Description {
            get {
                return ResourceManager.GetString("TrainingPlanHtmlExporter.UseAlternateRows.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use alternate rows.
        /// </summary>
        public static string TrainingPlanHtmlExporter_UseAlternateRows_DisplayName {
            get {
                return ResourceManager.GetString("TrainingPlanHtmlExporter.UseAlternateRows.DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set.
        /// </summary>
        public static string TrainingPlanSerie_Object {
            get {
                return ResourceManager.GetString("TrainingPlanSerie_Object", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max.
        /// </summary>
        public static string TrainingPlanSerieRepetitions_Max {
            get {
                return ResourceManager.GetString("TrainingPlanSerieRepetitions_Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MF.
        /// </summary>
        public static string TrainingPlanSerieRepetitions_MuscleFailure {
            get {
                return ResourceManager.GetString("TrainingPlanSerieRepetitions_MuscleFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        public static string TrainingPlanSerieRepetitions_Normalna {
            get {
                return ResourceManager.GetString("TrainingPlanSerieRepetitions_Normalna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AM.
        /// </summary>
        public static string TrainingPlanSerieRepetitions_PrawieMax {
            get {
                return ResourceManager.GetString("TrainingPlanSerieRepetitions_PrawieMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W.
        /// </summary>
        public static string TrainingPlanSerieRepetitions_Rozgrzewkowa {
            get {
                return ResourceManager.GetString("TrainingPlanSerieRepetitions_Rozgrzewkowa", resourceCulture);
            }
        }
    }
}
