//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BodyArchitect.Admin.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeleteOldProfilesParam", Namespace="http://MYBASERVICE.TK/IBodyArchitectAccessService/")]
    [System.SerializableAttribute()]
    public partial class DeleteOldProfilesParam : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool OnlyShowUsersField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool OnlyShowUsers {
            get {
                return this.OnlyShowUsersField;
            }
            set {
                if ((this.OnlyShowUsersField.Equals(value) != true)) {
                    this.OnlyShowUsersField = value;
                    this.RaisePropertyChanged("OnlyShowUsers");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SendMessageMode", Namespace="http://schemas.datacontract.org/2004/07/BodyArchitect.Service.Admin")]
    public enum SendMessageMode : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        All = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SelectedCountries = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ExceptSelectedCountries = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://MYBASERVICE.TK/", ConfigurationName="ServiceReference1.IAdminService")]
    public interface IAdminService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://MYBASERVICE.TK/IAdminService/DeleteOldProfiles", ReplyAction="http://MYBASERVICE.TK/IAdminService/DeleteOldProfilesResponse")]
        System.Collections.Generic.List<BodyArchitect.Service.V2.Model.UserDTO> DeleteOldProfiles(BodyArchitect.Admin.ServiceReference1.DeleteOldProfilesParam param);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://MYBASERVICE.TK/IAdminService/SendMessage", ReplyAction="http://MYBASERVICE.TK/IAdminService/SendMessageResponse")]
        void SendMessage(string topic, string message, BodyArchitect.Admin.ServiceReference1.SendMessageMode mode, System.Collections.Generic.List<int> countriesId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://MYBASERVICE.TK/IAdminService/DeleteUnusedImages", ReplyAction="http://MYBASERVICE.TK/IAdminService/DeleteUnusedImagesResponse")]
        System.Collections.Generic.List<BodyArchitect.Service.V2.Model.PictureInfoDTO> DeleteUnusedImages(BodyArchitect.Admin.ServiceReference1.DeleteOldProfilesParam param);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://MYBASERVICE.TK/IAdminService/DeleteOrphandExerciseRecords", ReplyAction="http://MYBASERVICE.TK/IAdminService/DeleteOrphandExerciseRecordsResponse")]
        void DeleteOrphandExerciseRecords(BodyArchitect.Admin.ServiceReference1.DeleteOldProfilesParam param);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAdminServiceChannel : BodyArchitect.Admin.ServiceReference1.IAdminService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AdminServiceClient : System.ServiceModel.ClientBase<BodyArchitect.Admin.ServiceReference1.IAdminService>, BodyArchitect.Admin.ServiceReference1.IAdminService {
        
        public AdminServiceClient() {
        }
        
        public AdminServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AdminServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdminServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdminServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<BodyArchitect.Service.V2.Model.UserDTO> DeleteOldProfiles(BodyArchitect.Admin.ServiceReference1.DeleteOldProfilesParam param) {
            return base.Channel.DeleteOldProfiles(param);
        }
        
        public void SendMessage(string topic, string message, BodyArchitect.Admin.ServiceReference1.SendMessageMode mode, System.Collections.Generic.List<int> countriesId) {
            base.Channel.SendMessage(topic, message, mode, countriesId);
        }
        
        public System.Collections.Generic.List<BodyArchitect.Service.V2.Model.PictureInfoDTO> DeleteUnusedImages(BodyArchitect.Admin.ServiceReference1.DeleteOldProfilesParam param) {
            return base.Channel.DeleteUnusedImages(param);
        }
        
        public void DeleteOrphandExerciseRecords(BodyArchitect.Admin.ServiceReference1.DeleteOldProfilesParam param) {
            base.Channel.DeleteOrphandExerciseRecords(param);
        }
    }
}
