//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BodyArchitect.Service.V2.Model.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ValidationStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BodyArchitect.Service.V2.Model.Localization.ValidationStrings", typeof(ValidationStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day number must be between 1 and 42..
        /// </summary>
        internal static string A6WEntryDTO_DayNumber_Range {
            get {
                return ResourceManager.GetString("A6WEntryDTO_DayNumber_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name can contain up to {5} characters..
        /// </summary>
        internal static string ActivityDTO_Name_Length {
            get {
                return ResourceManager.GetString("ActivityDTO_Name_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity must have a name.
        /// </summary>
        internal static string ActivityDTO_Name_Required {
            get {
                return ResourceManager.GetString("ActivityDTO_Name_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address 1 can contain up to {5} characters..
        /// </summary>
        internal static string AddressDTO_Address1_Length {
            get {
                return ResourceManager.GetString("AddressDTO_Address1_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address 2 can contain up to {5} characters..
        /// </summary>
        internal static string AddressDTO_Address2_Length {
            get {
                return ResourceManager.GetString("AddressDTO_Address2_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City can contain up to {5} characters..
        /// </summary>
        internal static string AddressDTO_City_Length {
            get {
                return ResourceManager.GetString("AddressDTO_City_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country can contain up to {5} characters..
        /// </summary>
        internal static string AddressDTO_Country_Length {
            get {
                return ResourceManager.GetString("AddressDTO_Country_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal code can contain up to {5} characters..
        /// </summary>
        internal static string AddressDTO_PostalCode_Length {
            get {
                return ResourceManager.GetString("AddressDTO_PostalCode_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a comment. It may contain up to {5} characters..
        /// </summary>
        internal static string BlogCommentDTO_Comment_Length {
            get {
                return ResourceManager.GetString("BlogCommentDTO_Comment_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a comment..
        /// </summary>
        internal static string BlogCommentDTO_Comment_NotNull {
            get {
                return ResourceManager.GetString("BlogCommentDTO_Comment_NotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BlogComment is required.
        /// </summary>
        internal static string BlogCommentOperation_BlogComment_NotNull {
            get {
                return ResourceManager.GetString("BlogCommentOperation_BlogComment_NotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must specify the application language..
        /// </summary>
        internal static string ClientInformation_ApplicationLanguage {
            get {
                return ResourceManager.GetString("ClientInformation_ApplicationLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must provide service version number for this client application.  It can have up to {5} characters..
        /// </summary>
        internal static string ClientInformation_Version_Length {
            get {
                return ResourceManager.GetString("ClientInformation_Version_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must provide service version number for this client application..
        /// </summary>
        internal static string ClientInformation_Version_NotNull {
            get {
                return ResourceManager.GetString("ClientInformation_Version_NotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short comment can have up to {5} characters..
        /// </summary>
        internal static string CommentEntryDTO_ShortComment_Length {
            get {
                return ResourceManager.GetString("CommentEntryDTO_ShortComment_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong email.
        /// </summary>
        internal static string CustomerDTO_EMail {
            get {
                return ResourceManager.GetString("CustomerDTO_EMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name can contain up to {5} characters..
        /// </summary>
        internal static string CustomerDTO_FirstName_Length {
            get {
                return ResourceManager.GetString("CustomerDTO_FirstName_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name can contain up to {5} characters..
        /// </summary>
        internal static string CustomerDTO_LastName_Length {
            get {
                return ResourceManager.GetString("CustomerDTO_LastName_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone can contain up to {5} characters..
        /// </summary>
        internal static string CustomerDTO_PhoneNumber_Length {
            get {
                return ResourceManager.GetString("CustomerDTO_PhoneNumber_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name can contain up to {5} characters..
        /// </summary>
        internal static string CustomerGroupDTO_Name_Length {
            get {
                return ResourceManager.GetString("CustomerGroupDTO_Name_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name can have up to {5} characters..
        /// </summary>
        internal static string EntryObjectDTO_Name_Length {
            get {
                return ResourceManager.GetString("EntryObjectDTO_Name_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description can contain up to {5} characters..
        /// </summary>
        internal static string ExerciseDTO_Description_Length {
            get {
                return ResourceManager.GetString("ExerciseDTO_Description_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name is required and can have up to {5} characters..
        /// </summary>
        internal static string ExerciseDTO_Name_Length {
            get {
                return ResourceManager.GetString("ExerciseDTO_Name_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is required..
        /// </summary>
        internal static string ExerciseDTO_Name_NotNull {
            get {
                return ResourceManager.GetString("ExerciseDTO_Name_NotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortcut is required and it should be unique. It can have up to {5} characters..
        /// </summary>
        internal static string ExerciseDTO_Shortcut_Length {
            get {
                return ResourceManager.GetString("ExerciseDTO_Shortcut_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortcut is required and it should be unique..
        /// </summary>
        internal static string ExerciseDTO_Shortcut_NotNull {
            get {
                return ResourceManager.GetString("ExerciseDTO_Shortcut_NotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url can have up to {5} characters..
        /// </summary>
        internal static string ExerciseDTO_Url_Length {
            get {
                return ResourceManager.GetString("ExerciseDTO_Url_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The message can have up to {5} characters..
        /// </summary>
        internal static string FriendInvitationDTO_Message_Length {
            get {
                return ResourceManager.GetString("FriendInvitationDTO_Message_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The message can have up to {5} characters..
        /// </summary>
        internal static string MessageDTO_Content_Length {
            get {
                return ResourceManager.GetString("MessageDTO_Content_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The topic is required and can have up to {5} characters..
        /// </summary>
        internal static string MessageDTO_Topic_Length {
            get {
                return ResourceManager.GetString("MessageDTO_Topic_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topic is required..
        /// </summary>
        internal static string MessageDTO_Topic_NotNull {
            get {
                return ResourceManager.GetString("MessageDTO_Topic_NotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About information may include up to {5} characters..
        /// </summary>
        internal static string ProfileDTO_AboutInformation_Length {
            get {
                return ResourceManager.GetString("ProfileDTO_AboutInformation_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthday date is not valid..
        /// </summary>
        internal static string ProfileDTO_Birthday {
            get {
                return ResourceManager.GetString("ProfileDTO_Birthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email address..
        /// </summary>
        internal static string ProfileDTO_EMail {
            get {
                return ResourceManager.GetString("ProfileDTO_EMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name can contain up to {5} characters..
        /// </summary>
        internal static string ReminderItemDTO_Name_Length {
            get {
                return ResourceManager.GetString("ReminderItemDTO_Name_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CopyStart must be lower than CopyEnd.
        /// </summary>
        internal static string SaveScheduleEntryRangeParam_CopyEndLowerCopyStart {
            get {
                return ResourceManager.GetString("SaveScheduleEntryRangeParam_CopyEndLowerCopyStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must specify CopyStart and CopyEnd..
        /// </summary>
        internal static string SaveScheduleEntryRangeParam_CopyParametersIncomplete {
            get {
                return ResourceManager.GetString("SaveScheduleEntryRangeParam_CopyParametersIncomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StartDay must be lower than EndDay..
        /// </summary>
        internal static string SaveScheduleEntryRangeParam_EndLowerStart {
            get {
                return ResourceManager.GetString("SaveScheduleEntryRangeParam_EndLowerStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StartTime must be lower than EndTime.
        /// </summary>
        internal static string ScheduleEntryDTO_EndLowerStart {
            get {
                return ResourceManager.GetString("ScheduleEntryDTO_EndLowerStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment can contain up to {5} characters..
        /// </summary>
        internal static string SerieDTO_Comment_Length {
            get {
                return ResourceManager.GetString("SerieDTO_Comment_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment can contain up to {5} characters..
        /// </summary>
        internal static string StrengthTrainingItemDTO_Comment_Length {
            get {
                return ResourceManager.GetString("StrengthTrainingItemDTO_Comment_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Super set group can contain up to {5} characters..
        /// </summary>
        internal static string StrengthTrainingItemDTO_SuperSetGroup_Length {
            get {
                return ResourceManager.GetString("StrengthTrainingItemDTO_SuperSetGroup_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SuperSet must contain at least two elements..
        /// </summary>
        internal static string SuperSet_Empty {
            get {
                return ResourceManager.GetString("SuperSet_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment can contain up to {5} characters..
        /// </summary>
        internal static string SuplementItemDTO_Content_Length {
            get {
                return ResourceManager.GetString("SuplementItemDTO_Content_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name can contain up to {5} characters..
        /// </summary>
        internal static string SuplementItemDTO_Name_Length {
            get {
                return ResourceManager.GetString("SuplementItemDTO_Name_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The author can contain up to {5} characters..
        /// </summary>
        internal static string SupplementCycleDefinitionDTO_Author_Length {
            get {
                return ResourceManager.GetString("SupplementCycleDefinitionDTO_Author_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The language of the plan must be defined..
        /// </summary>
        internal static string SupplementCycleDefinitionDTO_Language {
            get {
                return ResourceManager.GetString("SupplementCycleDefinitionDTO_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name can contain up to {5} characters..
        /// </summary>
        internal static string SupplementCycleDefinitionDTO_Name_Length {
            get {
                return ResourceManager.GetString("SupplementCycleDefinitionDTO_Name_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is required.
        /// </summary>
        internal static string SupplementCycleDefinitionDTO_Name_Required {
            get {
                return ResourceManager.GetString("SupplementCycleDefinitionDTO_Name_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Url can contain up to {5} characters..
        /// </summary>
        internal static string SupplementCycleDefinitionDTO_Url_Length {
            get {
                return ResourceManager.GetString("SupplementCycleDefinitionDTO_Url_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name can contain up to {5} characters..
        /// </summary>
        internal static string SupplementCycleDosageDTO_Name_Length {
            get {
                return ResourceManager.GetString("SupplementCycleDosageDTO_Name_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The supplement is required..
        /// </summary>
        internal static string SupplementCycleDosageDTO_Supplement_Required {
            get {
                return ResourceManager.GetString("SupplementCycleDosageDTO_Supplement_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name can contain up to {5} characters..
        /// </summary>
        internal static string SupplementCycleWeekDTO_Name_Length {
            get {
                return ResourceManager.GetString("SupplementCycleWeekDTO_Name_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment can contain up to {5} characters..
        /// </summary>
        internal static string SupplementDTO_Comment_Length {
            get {
                return ResourceManager.GetString("SupplementDTO_Comment_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name can contain up to {5} characters..
        /// </summary>
        internal static string SupplementDTO_Name_Length {
            get {
                return ResourceManager.GetString("SupplementDTO_Name_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url can have up to {5} characters..
        /// </summary>
        internal static string SupplementDTO_Url_Length {
            get {
                return ResourceManager.GetString("SupplementDTO_Url_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment can contain up to {5} characters..
        /// </summary>
        internal static string TrainingDayDTO_Comment_Length {
            get {
                return ResourceManager.GetString("TrainingDayDTO_Comment_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author can contains maximum {5} characters..
        /// </summary>
        internal static string TrainingPlan_Author_Length {
            get {
                return ResourceManager.GetString("TrainingPlan_Author_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workout plan must have at least one training day..
        /// </summary>
        internal static string TrainingPlan_Days_Empty {
            get {
                return ResourceManager.GetString("TrainingPlan_Days_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The plan includes at least two days with the same name. Each day must have a unique name..
        /// </summary>
        internal static string TrainingPlan_DaysName_Unique {
            get {
                return ResourceManager.GetString("TrainingPlan_DaysName_Unique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Each training day must have at least one entry (exercise)..
        /// </summary>
        internal static string TrainingPlan_Entries_Empty {
            get {
                return ResourceManager.GetString("TrainingPlan_Entries_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The language of the workout plan must be defined..
        /// </summary>
        internal static string TrainingPlan_Language {
            get {
                return ResourceManager.GetString("TrainingPlan_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of training plan is required and can contain up to {5} characters..
        /// </summary>
        internal static string TrainingPlan_Name_Length {
            get {
                return ResourceManager.GetString("TrainingPlan_Name_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workout plan must have a name..
        /// </summary>
        internal static string TrainingPlan_Name_NotNull {
            get {
                return ResourceManager.GetString("TrainingPlan_Name_NotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url to the workout description page/site can have up to {5} characters..
        /// </summary>
        internal static string TrainingPlan_Url_Length {
            get {
                return ResourceManager.GetString("TrainingPlan_Url_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workout day must have a unique name. It may contains maximum {5} characters..
        /// </summary>
        internal static string TrainingPlanDay_Name_Length {
            get {
                return ResourceManager.GetString("TrainingPlanDay_Name_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must choose an exercise for a workout day entry..
        /// </summary>
        internal static string TrainingPlanEntry_ExerciseId_NotSet {
            get {
                return ResourceManager.GetString("TrainingPlanEntry_ExerciseId_NotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the country of origin..
        /// </summary>
        internal static string UserDTO_CountryId {
            get {
                return ResourceManager.GetString("UserDTO_CountryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username must contain at least {3} and up to {5} characters..
        /// </summary>
        internal static string UserDTO_UserName_Length {
            get {
                return ResourceManager.GetString("UserDTO_UserName_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name is required..
        /// </summary>
        internal static string UserDTO_UserName_NotNull {
            get {
                return ResourceManager.GetString("UserDTO_UserName_NotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name can only have letters, numbers and _ (underscore). However, number cannot be the first character..
        /// </summary>
        internal static string UserDTO_UserName_SpecialCharacters {
            get {
                return ResourceManager.GetString("UserDTO_UserName_SpecialCharacters", resourceCulture);
            }
        }
    }
}
